### PR TITLE
FIX(server): Improve rememberchannelduration compare logic

### LINKED ISSUE #5639: rememberchannelduration option is ignored after restarting murmur
### Description

We use the ``rememberchannelduration`` server option on our servers. Last used channels are supposed to be remembered for 5 minutes for potential connection losses and such, but otherwise clients are expected to connect directly to the root channel. This usually works as expected. However, the murmur server is restarted over night every couple of weeks for maintenance.

**Expected Behavior**:
The server restart has no effect on the behavior of ``rememberchannelduration``. Clients connect to the root channel, except when they reconnect within the specified grace period.

**Actual Behavior**:
On the first connection of a client after the server restarted the remembered channel is used, even if the ``rememberchannelduration`` has long expired.

### Steps to reproduce

1. Start murmur with ``rememberchannelduration > 0``, ``rememberchannel = true`` and multiple permanent channels
2. Make sure the test user is registered
3. Make sure the channel remember delay works in regular use
4. Disconnect the user
5. Restart murmur
6. Let the ``rememberchannelduration`` expire
7. Reconnect

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

**Offending Code**:
Upon examining the code of the feature pull request #4147 we can see two things which are handled weirdly/wrongly:
1) For a reason I do not fully understand the ``last_disconnect`` field is set to ``NULL`` when starting murmur. [CODE](https://github.com/mumble-voip/mumble/pull/4147/files#diff-4212d89281db403601cb161873c4c42388491da7c05d388d3695fb0cfdcc23d1R460)
1) And the logic in ``ServerDB.cpp`` is broken when ``rememberchannel == true``, ``rememberchannelduration > 0`` and ``last_disconnect`` is equal to ``NULL``. ``rememberchannelduration`` is ignored and the server assigns the remembered channel anyway (as long as the channel still exists). [CODE](https://github.com/mumble-voip/mumble/pull/4147/files#diff-3334437d0370fc3870c709dbb6eae3f37e4e7830b6e56549f3ccd73306939afbR2001)

**Proposed Solution**:
To fix this murmur could
1) not set ``last_disconnect`` to ``NULL`` when starting.
2) fix the logic in ``ServerDB.cpp`` by returning ``-1`` in case ``last_disconnect`` is equal to ``NULL`` AND ``rememberchannelduration > 0``.

Or possibly both.

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Hartmnt**
### Checks

- [X] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### Todo

- [x] Extensive testing
- [x] Squash commits
- [ ] Rebase (if needed)

Fixes #5639

### CODE REVIEW

File: src/murmur/ServerDB.cpp [hunk 1]
```diff
@@ -2156,26 +2156,55 @@ int Server::readLastChannel(int id) {
...
+		QDateTime last_active, last_disconnect;
+
+		// NULL columns for last_active and last_disconnect will create empty invalid QDateTime objects.
+		// Using such objects with QDateTime::secsTo() will return 0 as per Qt specification.
+
+		if (!query.value(1).isNull()) {
+			last_active = QDateTime::fromString(query.value(1).toString(), Qt::ISODate);
+			last_active.setTimeSpec(Qt::UTC);
+		} else {
+			last_active = QDateTime();
```
Comment (Krzmbrzl) [inline src/murmur/ServerDB.cpp:2184]: This should be a no-op, as the default constructor is already invoked when declaring the variable above

File: src/murmur/ServerDB.cpp [hunk 2]
```diff
@@ -2156,26 +2156,55 @@ int Server::readLastChannel(int id) {
...
+		}
+
+		if (!query.value(2).isNull()) {
+			last_disconnect = QDateTime::fromString(query.value(2).toString(), Qt::ISODate);
+			last_disconnect.setTimeSpec(Qt::UTC);
+		} else {
+			last_disconnect = QDateTime();
```
Comment (Krzmbrzl) [inline src/murmur/ServerDB.cpp:2191]: Also a no-op

File: src/murmur/ServerDB.cpp [hunk 3]
```diff
@@ -2156,26 +2156,55 @@ int Server::readLastChannel(int id) {
...
 		}
+
+		if (last_active.secsTo(last_disconnect) <= 0) {
+			// Calculating the duration from last_disconnect is unreliable due to invalid values.
+			// Use the server uptime as time reference instead.
```
Comment (Krzmbrzl) [inline src/murmur/ServerDB.cpp:2196]:
```suggestion
			// last_disconnect < last_active. This can happen, if last_disconnect is invalid, because it has not been
			// updated properly (e.g. because the entire server was shut down while the user was still connected).
			// Us the server uptime as a reference point instead.
```

File: src/murmur/ServerDB.cpp [hunk 4]
```diff
@@ -2156,26 +2156,55 @@ int Server::readLastChannel(int id) {
...
+			last_disconnect = QDateTime::currentDateTime();
+			last_disconnect.setTimeSpec(Qt::UTC);
+			qint64 uptimeMSecs = static_cast< qint64 >(tUptime.elapsed() / 1000ULL);
```
Comment (Krzmbrzl) [inline src/murmur/ServerDB.cpp:2199]: Let's try to avoid Qt-specific types. Please use the 64-bit integer from the C++ standard instead: `std::uint64_t` (from `<stdint>`)

File: src/murmur/ServerDB.cpp [hunk 5]
```diff
@@ -2156,26 +2156,55 @@ int Server::readLastChannel(int id) {
...
+			last_disconnect = last_disconnect.addMSecs(-uptimeMSecs);
+		}
+
+		QDateTime now = QDateTime::currentDateTime();
+		now.setTimeSpec(Qt::UTC);
+
+		if (last_disconnect.secsTo(now) <= duration)
+			return cid;
```
Comment (Krzmbrzl) [inline src/murmur/ServerDB.cpp:2207]:
```suggestion
		if (last_disconnect.secsTo(now) <= duration) {
			return cid;
		}
```

**Review by Krzmbrzl — COMMENTED** [review]
I think if `last_active = NULL`, we should probably just abort and return `-1` as this indicates that we just don't have enough data for the given user for further processing.

File: src/murmur/ServerDB.cpp [hunk 6]
```diff
@@ -2156,26 +2156,55 @@ int Server::readLastChannel(int id) {
...
+
+		QDateTime last_active, last_disconnect;
+
+		// NULL columns for last_active and last_disconnect will create empty invalid QDateTime objects.
+		// Using such objects with QDateTime::secsTo() will return 0 as per Qt specification.
+
+		if (!query.value(1).isNull()) {
+			last_active = QDateTime::fromString(query.value(1).toString(), Qt::ISODate);
+			last_active.setTimeSpec(Qt::UTC);
```
[the remark this answers is not in the document]
Comment (Hartmnt) [reply src/murmur/ServerDB.cpp:2182]: Omitting ``setTimeSpec`` entirely would condense the code down quite a bit more.

**Comment by Hartmnt** [comment]
@Krzmbrzl 
> I think if `last_active = NULL`, we should probably just abort and return `-1` as this indicates that we just don't have enough data for the given user for further processing.

Wouldn't insufficient data fail at retrieving a row from the table? I would consider only ``last_active`` being ``NULL`` to be an error state and I think the server should honor the ``rememberchannelduration`` as accurately as possible in that case.

File: src/murmur/ServerDB.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (Krzmbrzl) [reply src/murmur/ServerDB.cpp:2182]: I think leaving it out should be fine.

File: src/murmur/ServerDB.cpp (hunk 4 above)
Comment (Krzmbrzl) [reply src/murmur/ServerDB.cpp:2196]: Yeah, I think that would in fact be best

**Comment by Hartmnt** [comment]
@Krzmbrzl I have now tested every code branch of ``readLastChannel`` in a build of the latest commit. As far as I can tell, they all work as intended. I am now awaiting your final decision on the outstanding discussions. I will then squash the pull request into a single commit.

File: src/murmur/ServerDB.cpp (hunk 5 above)
Comment (Krzmbrzl) [reply src/murmur/ServerDB.cpp]: Because it visually encloses the if-body, making the code easier to read and if in the future someone wants to add something to that body, they don't have to add the braces first. The emphasis lies on the first argument though.

**Comment by Krzmbrzl** [comment]
> Wouldn't insufficient data fail at retrieving a row from the table? 

I'm not entirely sure. And I think the respective column in the database is not marked as `NOT NULL` and thus it _could_ contain NULL values in which case the retrieving wouldn't fail for sure.

> I would consider only last_active being NULL to be an error state and I think the server should honor the rememberchannelduration as accurately as possible in that case.

I would also consider it an error state, which is why I think we should abort in this case. It doesn't seem wise to continue with data that we know is erroneous. In my experience that just calls for trouble down the line :)

**Comment by Hartmnt** [comment]
@Krzmbrzl 
> I would also consider it an error state, which is why I think we should abort in this case. It doesn't seem wise to continue with data that we know is erroneous. In my experience that just calls for trouble down the line :)

I am still not convinced on this particular point, but I changed it accordingly. I will build the server again locally and squash the commits after that. From my point of view the pull request is then ready to merge.

**Comment by Hartmnt** [comment]
@Krzmbrzl Oh you wanted braces around all if-statements... I was just following the previous implementations style and the surrounding code. What is the logic here? Or did the style guide change? I personally do not use ifs without braces whatsoever.

**Comment by Krzmbrzl** [comment]
> What is the logic here? Or did the style guide change?

Yeah, the style guide changed in the sense that I am now a maintainer of this software and I value code readability very highly. In the past this does not appear to have been a (big) concern to most, which is why you will find some really ghastly places in Mumble's source code xD
We never attempted to fix existing code though, but whenever I touch an area of the code, I try to adapt the code style as well. And that's what I also try to incentivize in my code reviews :)

**Comment by Hartmnt** [comment]
@Krzmbrzl 
> Yeah, the style guide changed in the sense that I am now a maintainer of this software and I value code readability very highly. In the past this does not appear to have been a (big) concern to most, which is why you will find some really ghastly places in Mumble's source code xD
> We never attempted to fix existing code though, but whenever I touch an area of the code, I try to adapt the code style as well. And that's what I also try to incentivize in my code reviews :)

I see. I was initially confused why you were requesting to change a single if-statement.


> EDIT: Speaking of code style though: Your code is not formatted correctly. Could you run clang-format on the files you touched to streamline the code formatting?

Done, but if this actually improved code readability in this particular case is up for debate. ;)

**Comment by Krzmbrzl** [comment]
Hm... It still doesn't like your formatting :eyes:

**Comment by Krzmbrzl** [comment]
> but I suppose that was changed due to character line limits.

Yes, indeed.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thanks for fixing this :+1:

**Comment by Krzmbrzl** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.4.x|[](https://github.com/mumble-voip/mumble/pull/5652)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
