### PR TITLE
Fix echo cancellation setting not saved

### LINKED ISSUE #4761: Echo cancellation settings not saved
Just downloaded and built the last development version of Mumble, and it looks like if I close and reopen it, the echo cancellation settings is lost and defaults back to "Disabled".

I tried only on Linux, don't know if it occurs on other platforms.

**Steps to Reproduce**
1. Build the latest Mumble development version
2. Open Mumble and open Configure > Settings > Audio Processing and select Mixed echo cancellation for example
3. Close and reopen Mumble
4. Check the echo cancellation settings

The expected behavior is that the setting should be preserved, the observed behavior is that it defaults back to "Disabled".

### PR DESCRIPTION
**Pull request by Krzmbrzl**
This fixes a few regressions introduced in #4694 affecting the echo cancellation settings.

Fixes #4761

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Typo in 42128806e8d96ebceeb1abceb8f856a88e43eae3's message:
> In #4694 (dafbce2 to be precise)
refactored how the echo cancellation setting was stored.
During that refactoring however the wrong macro was used for actually
saving the setting, causing it to not actually being saved.

The `In` at the beginning should be removed.

File: src/mumble/Settings.cpp [hunk 1]
```diff
@@ -401,7 +401,16 @@ Settings::Settings() {
 	bJackStartServer  = false;
 	bJackAutoConnect  = true;
 
-	echoOption = EchoCancelOptionID::DISABLED;
+#ifdef Q_OS_MAC
```
Comment (davidebeatrici) [inline src/mumble/Settings.cpp:404]:
```c
#ifdef Q_OS_MACOS
```

From https://doc.qt.io/qt-5/qtglobal.html#Q_OS_MAC:
> Deprecated synonym for **Q_OS_DARWIN**. Do not use.

File: src/mumble/Settings.cpp [hunk 2]
```diff
@@ -401,7 +401,16 @@ Settings::Settings() {
...
+	// On macOS Speex can't be used, so we default to Apple's custom echo cancellation mode
+	// Note that this only seems to work with when using the builtin microphone and the builtin speakers. It
```
Comment (davidebeatrici) [inline src/mumble/Settings.cpp:406]: `// Note that this only seems to work when using the built-in microphone and the built-in speakers. It`

File: src/mumble/Settings.cpp [hunk 3]
```diff
@@ -768,7 +770,33 @@ void Settings::load(QSettings *settings_ptr) {
 	SAVELOAD(qsAudioOutput, "audio/output");
 	SAVELOAD(bWhisperFriends, "audio/whisperfriends");
 	SAVELOAD(bTransmitPosition, "audio/postransmit");
-	LOADFLAG(echoOption, "audio/echooptionid");
+
+	if (settings_ptr->contains("audio/echooptionid")) {
+		// Load the new echo cancel option instead
+		LOADFLAG(echoOption, "audio/echooptionid");
+	} else {
+#ifndef Q_OS_MAC
```
Comment (davidebeatrici) [inline src/mumble/Settings.cpp:778]:
```c
#ifndef Q_OS_MACOS
```

File: src/mumble/Settings.cpp [hunk 4]
```diff
@@ -768,7 +770,33 @@ void Settings::load(QSettings *settings_ptr) {
...
+		// Compatibility layer for overtaking the old (now deprecated) settings
+		// This block should only be called once at the first start of the new Mumble version
+		// As echo cancellation was not available on macOS before, we don't have to run this compatibility
+		// code on macOS (instead simply use the new default as set in the constructor).
+		bool deprecatedEcho      = false;
+		bool deprecatedEchoMulti = false;
```
Comment (davidebeatrici) [inline src/mumble/Settings.cpp:784]: `auto` can be used here without hiding the data type, as we explicitly set the variable's value.

**Review by davidebeatrici — COMMENTED** [review]
Mostly cosmetic things.

File: src/mumble/Settings.cpp (hunk 4 above)
Comment (Krzmbrzl) [reply src/mumble/Settings.cpp:784]: But there is also no gain whatsoever in doing so

File: src/mumble/Settings.cpp (hunk 1 above)
Comment (Krzmbrzl) [reply src/mumble/Settings.cpp:404]: Interestingly we are using `Q_OS_MAC` in a lot of places in this file. I will add a commit that fixes that as well

Comment (davidebeatrici) [reply src/mumble/Settings.cpp]: Not only in this file, unfortunately.

We could simply perform a search & replace to fix all instances.

Comment (Krzmbrzl) [reply src/mumble/Settings.cpp]: That'd probably be worth it in order to avoid copy&paste errors as this one.
Do you want to do it or shall I?
