### PR TITLE
 FIX(tts): OmitScope/OmitAuthor no longer reads HTML-formatted message

### LINKED ISSUE #4309: "Omit Message Scope" makes the TTS engine read the actual HTML of the message
**Describe the bug**
The new option "Omit Message Scope" introduced in #3677 makes the TTS engine read the actual HTML.

**Steps to Reproduce**
1. Set Omit Message Scope in settings
2. Let someone else send you a message
3. Hear HTML-Tags
4. Render HTML in your mind

**Expected behavior**
The same message should be read, just without the scope.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Mumble compiled from master

### PR DESCRIPTION
**Pull request by Popkornium18**
The new features "Omit Message Scope" and "Omit Message Author" where
somewhat broken.
The problems are adressed by transforming the message from HTML to
plaintext and creating a new TTS string that either contains no prefix
or just the scope or the author.

Fixes #4309

### CODE REVIEW

File: src/mumble/Messages.cpp [hunk 1]
```diff
@@ -888,30 +887,32 @@ void MainWindow::msgTextMessage(const MumbleProto::TextMessage &msg) {
...
+			return plain;
 		}
-	}
+		const QString prefix = g.s.bTTSNoScope ? plainName : target;
+		return tr("%1: %2").arg(prefix).arg(plain);
+	}();
 
 	g.l->log(privateMessage ? Log::PrivateTextMessage : Log::TextMessage,
-	         tr("%2%1: %3").arg(name).arg(target).arg(u8(msg.message())),
+	         tr("(%2) %1: %3").arg(name).arg(target).arg(u8(msg.message())),
```
Comment (Popkornium18) [inline src/mumble/Messages.cpp:912]: If target were empty this would lead to wrong formatting. Could this ever be the case?

**Comment by Popkornium18** [comment]
Wtf why are Mac and Windows complaining about forward declaration but Linux compiles fine? :thinking:

**Comment by Krzmbrzl** [comment]
> Wtf why are Mac and Windows complaining about forward declaration but Linux compiles fine?

Welcome to c++'s compiler hell where every compiler works (slightly) differently :shrug:

File: src/mumble/Messages.cpp (hunk 1 above)
Comment (Krzmbrzl) [reply src/mumble/Messages.cpp:913]: I think atm this is not possible, but maybe this could change in the future. Thus I'd say it's probably better to check for this case explicitly than implicitly relying on it to never occur ^^

Comment (Popkornium18) [reply src/mumble/Messages.cpp]: Ok, I made some changes to account for that.

**Comment by Krzmbrzl** [comment]
Thanks for fixing this :)
