### PR TITLE
FIX(client): Prefer selected tree item for context menu creation

### LINKED ISSUE #3090: Channel main menu items do not operate on selected channel
All of the channel main menu items operate on the last channel that was right-clicked on, not the currently selected channel.

To reproduce:
1. Join a channel's root server
2. Right click on some other channel in the server
3. Close the popup menu without doing anything
4. Click once on the root channel so it is selected
5. Click Channel -> Edit...

You expect to edit the ACL of the root channel, since it is currently selected, but actually you are editing the channel that you right clicked on in step 2.

### PR DESCRIPTION
**Pull request by Hartmnt**
Fixes #3090

Thise merge request contains 2 commits:

1) The shared/copied code for user, listener and channel context menu target selection is unified

2) Adds a ``nullptr`` check to make sure the selected user/channel is used in context menus rather than the most recently used context item. This was an oversight in 4f5089fe30a

## TODO:

- [x] Refactor
- [x] Check listener context menu
- [ ] Rebase if necessary

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
> Seperate commit for refactor?

I think it would depend on the scope of Tür refactoring. If the refactoring is only about centralizing the current implementations in order to fix this bug only once, in a single place, using a single commit for refactoring + fixing sounds fine.

If however the refactoring is a bit bigger, then I would consider a separate refactoring commit more appropriate.

Alternatively, you could also first create the refactoring commit and then fix the bug only in the refactored code (in a separate commit)

**Comment by Hartmnt** [comment]
I will have to think about all the refactor possibilities a bit

File: src/mumble/MainWindow.cpp [hunk 1]
```diff
@@ -741,6 +742,36 @@ ClientUser *MainWindow::getContextMenuUser() {
 	return nullptr;
 }
 
+std::tuple< ClientUser *, Channel * > MainWindow::getContextMenuTargets() {
```
Comment (Krzmbrzl) [inline src/mumble/MainWindow.cpp:745]: I think a dedicated struct for the return value probably increases code readability:
```cpp
struct ContextMenuTarget {
  ClientUser *user = nullptr;
  Channel *channel = nullptr;
};
```

Comment (Hartmnt) [reply src/mumble/MainWindow.cpp]: For future reference, this would probably make a good entry point for #3897

File: src/mumble/MainWindow.cpp [hunk 2]
```diff
@@ -741,6 +741,36 @@ ClientUser *MainWindow::getContextMenuUser() {
 	return nullptr;
 }
 
+ContextMenuTarget MainWindow::getContextMenuTargets() {
+	ClientUser *p = nullptr;
```
Comment (Krzmbrzl) [inline src/mumble/MainWindow.cpp:745]: I would simply create a `ContextMenuTarget` object here. Then you don't need two separate variables floating around and the `nullptr` initialization is implicit.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Hartmnt** [comment]
Note before merging that this merge request currently runs against fewer automated tests  than usual for some reason!

**Comment by Krzmbrzl** [comment]
Hm, it seems like the Azure checks for some reason did not trigger. Afaik I can't trigger them manually though,so let's just merge as is :shrug:
