### PR TITLE
Backport "BUILD: BSD fixes"

### LINKED ISSUE #5888: Bug fixes on master missing in 1.4.x branch
### The issue

Is there any chance the following commits could make it into the next release?
Then OpenBSD can stop carrying them locally.

42ad5ed
ccbacbf
a707213
0c769d8
904bae1

### Mumble version

1.4.287

### Mumble component

Both

### OS

OpenBSD

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Krzmbrzl**
Fixes #5888 

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

File: src/ProcessResolver.cpp [hunk 1]
```diff
@@ -239,7 +239,7 @@ void ProcessResolver::doResolve() {
 #	ifdef KVM_NO_FILES
 	kvm_t *kd = kvm_openfiles(NULL, NULL, NULL, KVM_NO_FILES, error);
 #	else
-	kvm_t *kd = kvm_openfiles(NULL, _PATH_DEVNULL, NULL, O_RDONLY, error);
+	kvm_t *kd                     = kvm_openfiles(NULL, _PATH_DEVNULL, NULL, O_RDONLY, error);
```
Comment (davidebeatrici) [inline src/ProcessResolver.cpp:242]: ?
