### PR TITLE
FIX(client): Echo cancellation options not translated

### LINKED ISSUE #4993: Echo cancellation options not translated
**Describe the bug**
As reported here: https://github.com/mumble-voip/mumble/issues/4359#issuecomment-835878716
The Strings `Mixed echo cancellation (Speex)` and `Multichannel echo cancellation (Speex)` are not translated

**Steps to Reproduce**
1. Open AudioInput settings (with language != English)

@Kissaki correctly [pointed out](https://github.com/mumble-voip/mumble/issues/4359#issuecomment-837192693) that this might be because these Strings are defined in a static variable
https://github.com/mumble-voip/mumble/blob/baeddddec4c301389a088a9f7059a4b5d28c7dd1/src/mumble/EchoCancelOption.h#L29-L43
and thus they might get instantiated before the needed translator object is installed.
What contradicts this theory a bit is that the `Disabled` option seems to be translated just fine. Maybe `Disabled` is a String that is translatable by the default translator though (if there is such a thing) :shrug:

### PR DESCRIPTION
**Pull request by Krzmbrzl**
These Strings were not translated because as global static variables
they were created before the necessary translators are installed.

This commit fixes this by making sure the containing EchoCancelOption
objects are created lazily (at the time they are needed for the first
time), thus causing a delaying instantiation.

Fixes #4993

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

File: src/mumble/EchoCancelOption.h [hunk 1]
```diff
@@ -23,23 +24,11 @@ struct EchoCancelOption {
...
-	// Available only on Apple devices
-	{ EchoCancelOptionID::APPLE_AEC, QObject::tr("EXPERIMENTAL: Acoustic echo cancellation (Apple)."),
-	  QObject::tr("The support for this option is experimental only! This option works best when using built-in "
-				  "microphone and speaker.") }
+	/// @returns A vector of EchoCancelOption objects in the same order as specified in the
+	/// EchoCancelOptionID enum. Thus the enums can be used as an index for the returned vector.
+	static const std::vector< EchoCancelOption > &getOptions();
 };
 
+
```
Comment (Kissaki) [inline src/mumble/EchoCancelOption.h:33]: Accidental empty line added?

File: src/mumble/EchoCancelOption.cpp [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+
+#include <QObject>
+
+const std::vector< EchoCancelOption > &EchoCancelOption::getOptions() {
+	// Note that we have to create this list latily (at the time it is needed for the first time) in order
+	// to make sure that there actually is a translator installed that can translate these Strings. If we
+	// create these objects too early (e.g. by making them a static variable in global namespace), the Strings
+	// will not get translated.
+
+	// Please strictly follow the order of the EchoCancelOptionID enum when adding items to this array.
```
Comment (Kissaki) [inline src/mumble/EchoCancelOption.cpp:16]: I see this is taken over, but I think we should make this a hard MUST. The method now specifies that it is indexable as such, so this MUST remain true.

```suggestion
	// The item order MUST follow the EchoCancelOptionID enum.
```

```suggestion
	// The item order MUST follow the EchoCancelOptionID enum so they remain accessible by index by enum value.
```

File: src/mumble/EchoCancelOption.cpp [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+// Use of this source code is governed by a BSD-style license
+// that can be found in the LICENSE file at the root of the
+// Mumble source tree or at <https://www.mumble.info/LICENSE>.
+
+#include "EchoCancelOption.h"
+
+#include <QObject>
+
+const std::vector< EchoCancelOption > &EchoCancelOption::getOptions() {
+	// Note that we have to create this list latily (at the time it is needed for the first time) in order
```
Comment (Kissaki) [inline src/mumble/EchoCancelOption.cpp:11]: latily?

```suggestion
	// Note that we have to create this list late (at the time it is needed for the first time) in order
```

**Review by Kissaki — APPROVED** [review]
Otherwise LGTM

File: src/mumble/EchoCancelOption.cpp (hunk 3 above)
Comment (Krzmbrzl) [reply src/mumble/EchoCancelOption.cpp:11]: *lazily xD
