### PR TITLE
FIX(client): Correctly remember muted state across restarts

### LINKED ISSUE #6393: un-mute and un-deafen only un-deafens after restart
### Description

if exiting mumble while mute and deafen are enabled, and then using a hotkey to disable mute and deafen the next time it's run, the mic remains muted

### Steps to reproduce

1. assign a hotkey to deafen self (Control_L + Super_L)
2. deafen self
3. restart mumble
4. use assigned hotkey to un-mute and un-deafen self
5. observe that the mic remains muted

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Manjaro Linux, KDE, Mumble installed from Arch repo

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Hartmnt**
Previously, only the "mute" and "deaf" states were saved to the settings file. However, when a user deafens themselves without muting first, Mumble will automatically unmute the user as soon as they undeafen. The "autoUnmute" state was not saved in the settings though, leading to the state "deafened (muted implied)" being reduced to "deafened and muted".

This commit moves the autoUnmute state from being a local member of MainWindow to the settings file allowing to preserve the "deafened (muted implied)" state.

Fixes #6393

### CODE REVIEW

File: src/mumble/SettingsKeys.h [hunk 1]
```diff
@@ -37,6 +37,7 @@ namespace SettingsKeys {
 // Audio settings
 const SettingsKey MUTE_KEY                                    = { "mute" };
 const SettingsKey DEAF_KEY                                    = { "deaf" };
+const SettingsKey AUTO_UNMUTE_KEY                             = { "auto_unmute" };
```
Comment (davidebeatrici) [inline src/mumble/SettingsKeys.h:40]:
```suggestion
const SettingsKey AUTO_UNMUTE_KEY                             = { "auto_unmute" };
const SettingsKey MUTE_KEY                                    = { "mute" };
const SettingsKey DEAF_KEY                                    = { "deaf" };
```

File: src/mumble/SettingsMacros.h [hunk 2]
```diff
@@ -21,6 +21,7 @@
 #define AUDIO_SETTINGS                                                                      \
 	PROCESS(audio, MUTE_KEY, bMute)                                                         \
 	PROCESS(audio, DEAF_KEY, bDeaf)                                                         \
+	PROCESS(audio, AUTO_UNMUTE_KEY, autoUnmute)                                             \
```
Comment (davidebeatrici) [inline src/mumble/SettingsMacros.h:24]:
```suggestion
	PROCESS(audio, AUTO_UNMUTE_KEY, autoUnmute)                                             \
	PROCESS(audio, MUTE_KEY, bMute)                                                         \
	PROCESS(audio, DEAF_KEY, bDeaf)                                                         \
```

Comment (Hartmnt) [reply src/mumble/SettingsMacros.h:24]: This is just the order. I did not mess up the whitespace, right?

Comment (davidebeatrici) [reply src/mumble/SettingsMacros.h:24]: Just the order.

**Review by davidebeatrici — APPROVED** [review]

**Review by Krzmbrzl — APPROVED** [review]
While touching this anyway, I think we could rename the flag to something like `unmute_on_undeaf`

**Comment by davidebeatrici** [comment]
Yeah, the current name is not clear.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.5.x|[](https://github.com/mumble-voip/mumble/pull/6448)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/mumble-voip/mumble/actions/runs/9337145628) for details
