### PR TITLE
REFAC(client): Don't use deprecated mutex ctor

### LINKED ISSUE #4973: QMutex recursion mode is deprecated
**Describe the bug**
Newer QT version seems to have deprecated QMutex recursion mode.

**Steps to Reproduce**
1. Use the live 5.15 qtcore git branch
2. Try to compile mumble
3. Compilation fails with the following error:

```
/var/tmp/portage/media-sound/mumble-9999/work/mumble-9999/src/mumble/Plugin.cpp:18:45: error: ‘QMutex::QMutex(QMutex::RecursionMode)’ is deprecated: Use QRecursiveMutex instead of a recursive QMutex [-Werror=deprecated-declarations]
   18 | QMutex Plugin::s_idLock(QMutex::NonRecursive);
      |                                             ^
In file included from /usr/include/qt5/QtCore/QMutex:1,
                 from /var/tmp/portage/media-sound/mumble-9999/work/mumble-9999/src/mumble/Plugin.h:15,
                 from /var/tmp/portage/media-sound/mumble-9999/work/mumble-9999/src/mumble/Plugin.cpp:6:
/usr/include/qt5/QtCore/qmutex.h:140:14: note: declared here
  140 |     explicit QMutex(RecursionMode mode);
      |              ^~~~~~
cc1plus: all warnings being treated as errors
```

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Version: Mumble git master

### PR DESCRIPTION
**Pull request by Krzmbrzl**
In the latest Qt version, specifying a recrsion mode when creating a
mutex was deprecated in favor of QRecursiveMutex being used for the
cases where recursion is needed.

Given that we only ever needed non-recursive mutexes, all we had to do
was to remove the argument to the ctor.

Ref.: Upstream commit deprecating that ctor:
https://github.com/qt/qtbase/commit/d4b206b246caf9b49110526585693ab629609d99

Fixes #4973

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Review by Kissaki — APPROVED** [review]

File: src/mumble/ServerHandler.cpp [hunk 1]
```diff
@@ -59,7 +59,7 @@
 
 // Init ServerHandler::nextConnectionID
 int ServerHandler::nextConnectionID = -1;
-QMutex ServerHandler::nextConnectionIDMutex(QMutex::Recursive);
+QMutex ServerHandler::nextConnectionIDMutex;
```
Comment (vimpostor) [inline src/mumble/ServerHandler.cpp:62]: This seems wrong, it was using Recursive mode unlike above. Are you sure this mutex didn't need recursive mode? @Krzmbrzl

Comment (Krzmbrzl) [reply src/mumble/ServerHandler.cpp:62]: Oh lol. You are right :eyes:

Comment (Krzmbrzl) [reply src/mumble/ServerHandler.cpp:62]: In this particular case however it doesn't matter since the mutex should have been non-recursive anyways. It is only ever used in a single place (constructor of `ServerHandler`) and therefore it does not have to be recursive.
That was probably an oversight from the initial implementation that was now accidentally fixed xD

Thanks for pointing this out though! :+1:

Comment (Kissaki) [reply src/mumble/ServerHandler.cpp:62]: Damn, I saw that and got confused between diffs and files and local, and somehow lost that train of thought/verifying. lol
