### PR TITLE
FIX(client, ui): Fix log scroll position after loading resources

### LINKED ISSUE #2504: Mumble log scrolls to top instead of bottom on some Qt versions (4.8, 5.2, maybe more?)
From IRC:

```
22:27:27 <jemu> hiho, it seems that since some newer snapshot versions of mumble the chat scrolls to the top (as opposed to the bottom) when an image is posted. is this a known problem? is it maybe related to some older qt5 versions?
22:29:03 <@mkrautz> jemu: where are you seeing it?
22:29:57 <jemu> mkrautz: two people have reported this to me, one is one ubuntu trusty + snapshot ppa the other on windows 7 + official snapshot build
22:30:46 <jemu> mkrautz: sorry, i confused something, both are linux (one is ubutnu trusty + snapshot ppa, the other is a debian system)
22:31:03 <jemu> it works perfectly fine on my system (gentoo + manually build)
22:33:01 <jemu> i couldn't find a bug report, only some older ones with the opposite issue (not scrolling at all)
22:33:02 <@mkrautz> is the debian system using debian's own package?
22:33:13 <@mkrautz> if so, that would probably have the bug
22:33:29 <jemu> the debian user has done a custom build from git master
22:33:57 <jemu> the ubuntu user has: 1.3.0 (1.3.0~1326~gf4ca0cf~snapshot-1~ppa1~trusty1)
22:34:40 <@mkrautz> OK
22:34:48 <@mkrautz> seems like it's possibly an issue with older versions of Qt then, hmm...
22:34:58 <@mkrautz> jemu: that's pretty old
22:35:36 <@mkrautz> (not that anything should have changed in that regard, but ... it's still a bit oldold)
22:35:41 <@mkrautz> eh, old* :)
22:35:58 <@mkrautz> OK, trust has Qt 5.2
22:36:05 <@mkrautz> and the Debian user is... maybe on Qt 4?
22:37:14 <jemu> mkrautz: yes, the debian user is still on Qt 4
22:37:41 <@mkrautz> OK, I would expect the Qt 4 to be broken in that regard, actually :(
22:37:50 <@mkrautz> the Qt 4 version*
22:38:04 <@mkrautz> I seem to be missing a lot of words today :)
22:38:07 <jemu> good (or bad, depends on context), what about Qt 5.2?
22:38:27 <@mkrautz> jemu: I have no idea about that :(
22:41:21 <jemu> mkrautz: we have updated to 1508 on the ubuntu system, issue persists
22:41:38 <jemu> so maybe we should update from trusty to xenial?
22:41:54 <@mkrautz> jemu: well, it's a bug I'd like to fix... so :)
22:42:15 <jemu> ok, something we can do to help?
22:42:56 <@mkrautz> jemu: if the debian user could try to build 1.2.16 w/ qt 4 and check if that works, that would help :)
```

### PR DESCRIPTION
**Pull request by dexgs**
In my previous PR (https://github.com/mumble-voip/mumble/pull/6290) addressing this bug, I wrote:
> The issue seems to be caused by the scrollbar sometimes being in an
> inconsistent state immediately after a message is sent, but not any
> longer.
>
> My workaround is to add a call to QApplication::processEvents before
> setting the scrollbar to its maximum position to avoid the inconsistent
> state.

I have found that this change only reduces the likelihood of the incorrect scroll behaviour from happening: it is still reproducible after the log grows past a certain size.

In my testing since then, the cause of the "inconsistent state" described previously seems to be the following: When images (whose contents are stored in a base64-encoded data URL) are inserted into the log, they are
not loaded immediately. Instead, they are "fetched" (although no actual network request occurs) by the `loadResource` implementation on `LogDocument`. The "fetching" is triggered by the call to `setHtml` in the `Log::validHtml` method. However, the code which sets the scroll bar to stay at the bottom runs immediately (i.e. not asynchronously) in the
`Log::log` method. There also seems to be a hack that forces a re-layout by sending a "font changed" event.

The intended behaviour appears to be that when a log entry is added the log will scroll to the bottom if the entry is a message sent by the user themselves, OR if the log was already scrolled to the bottom before the entry was added.

The previous solution in place addressing the asynchronous image loading was dispatching a `LogDocumentResourceAddedEvent` when the image is loaded whose handler scrolls the log to the bottom, but this causes 2 problems:

First, the handler for this event always scrolls the log to the bottom no matter what, which means messages containing images are handled differently from the intended scrolling behaviour, i.e. messages containing images ALWAYS cause the log to scroll to the bottom instead of obeying the rules described above.

Second, it seemingly causes the issue described in https://github.com/mumble-voip/mumble/issues/2504. It looks like there's a race condition when the scroll position is set from the main thread as well as in an event handler. I couldn't get to the bottom of the exact source of the issue because there is so much deferred execution going on, but I am confident that adding resources/forcing re-layout events from an event handler is to blame.

My current solution is to remove as much of this asynchronous code as possible. The use of a `QNetworkReply` seems to be leftover from when Mumble supported remote images in chat. As described above, this implementation was problematic and its complexity is no longer needed, so I changed the implementation of `LogDocument::loadResource` to simply check that the image URL is valid and has the `data://` scheme and then just fall back to QTextDocument::loadResource`.

Implementing the solution this way eliminates the need for `LogDocumentResourceAddedEvent` because everything happens in order as expected and there is no need to "correct" the scroll value after the image gets loaded. I therefore removed this class and the associated code.

The default behaviour of `QTextEdit` is that it scrolls to the bottom whenever contents are added. `LogTextBrowser::scrollLogToBottom` seems to be a workaround to try to get the log to stay at the bottom despite
the scroll bar jumping issue. With my solution, this method can be removed, and we only need to worry about "restoring" the previous scroll value when a message from another user arrives and the log isn't already scrolled to the bottom.

### CODE REVIEW

**Comment by dexgs** [comment]
PR is a draft for now because I'm still testing the changes

**Comment by dexgs** [comment]
@Krzmbrzl Can you take a look at this?

**Comment by dexgs** [comment]
> Please also validate that this fixes #6328

image

@Hartmnt I tried linking to Team Fortress 2 and couldn't reproduce #6328.

This PR reverts the changes from the offending PR, so I think it will fix the issue.

File: src/mumble/Log.cpp [hunk 1]
```diff
@@ -776,9 +779,7 @@ void Log::log(MsgType mt, const QString &console, const QString &terse, bool own
 		// Set the line height of the trailing blank line to zero
 		tc.setBlockFormat(bf);
 
-		if (scroll || ownMessage)
-			tlog->scrollLogToBottom();
-		else
+		if (restoreScroll)
```
Comment (Hartmnt) [inline src/mumble/Log.cpp:782]: Please use ``{`` for single line if statements

```
if (restoreScroll) {
	tlog->setLogScroll(oldscrollvalue);
}
```

**Review by Hartmnt — COMMENTED** [review]
Compiled and tested it. It indeed fixes #6328

File: src/mumble/CustomElements.cpp [hunk 2]
```diff
@@ -22,33 +22,17 @@
...
-void LogTextBrowser::scrollLogToBottom() {
-	// Without the call to processEvents, the scrollbar sometimes ends up in an
-	// incorrect position after an image is sent to the chat log.
-	//
-	// See: https://github.com/mumble-voip/mumble/issues/2504
-	QApplication::processEvents();
-
-	verticalScrollBar()->setValue(verticalScrollBar()->maximum());
+bool LogTextBrowser::isScrolledToBottom() {
+	QScrollBar *scrollBar = verticalScrollBar();
```
Comment (Krzmbrzl) [inline src/mumble/CustomElements.cpp:34]:
```suggestion
	const QScrollBar *scrollBar = verticalScrollBar();
```

File: src/mumble/Log.cpp [hunk 3]
```diff
@@ -722,7 +722,10 @@ void Log::log(MsgType mt, const QString &console, const QString &terse, bool own
 
 		LogTextBrowser *tlog     = Global::get().mw->qteLog;
 		const int oldscrollvalue = tlog->getLogScroll();
-		const bool scroll        = (oldscrollvalue == tlog->getLogScrollMaximum());
+		// Restore the previous scroll position after inserting a new message
+		// if the message was not sent by the user AND the chat log is not
+		// scrolled all the way down.
+		const bool restoreScroll = !ownMessage && !tlog->isScrolledToBottom();
```
Comment (Krzmbrzl) [inline src/mumble/Log.cpp:728]:
```suggestion
		const bool restoreScroll = !(ownMessage || tlog->isScrolledToBottom());
```
I think this form is easier parsable by fellow humans :)

**Review by Krzmbrzl — APPROVED** [review]
Now that's a neat simplification of the code :+1: 

LGTM

**Comment by dexgs** [comment]
I've pushed all the suggested corrections

**Review by Hartmnt — APPROVED** [review]
