### PR TITLE
FIX(client, macOS): Move Quit menu to application menu on macOS

### LINKED ISSUE #7151: Move the Quit button to the "Mumble" application menu on macOS
### Context

N/A

### Description

Currently on macOS, the "Quit Mumble" menu option is under the "Server" menu

Image

In a typical macOS application, the quit option is usually under the application menu

Image

which isn't the case for Mumble (sometimes "Quit Mumble" will show up under this menu for some reason)

Image

Tested with the latest Mumble development snapshot (1.6.870 x86_64)

### Mumble component

Client

### OS-specific?

Yes

### Additional information

N/A

### PR DESCRIPTION
**Pull request by maxer137**
On macOS, the "Quit Mumble" option was incorrectly placed under the Server menu instead of the standard application menu. This commit adjusts the menu placement so that the quit action appears under the application menu on macOS, aligning with typical macOS UI conventions.

It also disables the custom icon for the preferences option. This too is to align with typical macOS UI conventions.

- Exclude Quit action from Server menu on macOS
- Set `menuRole` of Quit action to `QAction::QuitRole` in UI file
- Hide custom preferences icon in menu on macOS

Implements #7151

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by maxer137** [comment]
Before changes:
<table>
<tr>
  <td>Mumble menubar options before commit changes. Shows preferences with blue gear icon. Quit options not present</td>
  <td>Mumble server menubar options before commit changes. Shows quit option at bottom.</td>
</tr>
</table>
After changes:
<table>
<tr>
  <td>Mumble menubar options after commit changes. Shows preferences with default MacOS gear icon. Quit options present</td>
  <td>Mumble server menubar options after commit changes. Quit option not present.</td>
</tr>
</table>

File: src/mumble/MainWindow.cpp [hunk 1]
```diff
@@ -1666,8 +1669,10 @@ void MainWindow::on_qmServer_aboutToShow() {
 	qmServer->addAction(qaServerTokens);
 	qmServer->addAction(qaServerUserList);
 	qmServer->addAction(qaServerBanList);
+#ifndef Q_OS_MACOS
 	qmServer->addSeparator();
 	qmServer->addAction(qaQuit);
+#endif
```
Comment (Hartmnt) [inline src/mumble/MainWindow.cpp]: Could you please add a comment here on why we do that? Maybe even add a link to the GitHub issue.

**Review by Hartmnt — COMMENTED** [review]
You can ignore the coderabbit suggestion as it is BS

File: src/mumble/MainWindow.cpp (hunk 1 above)
Comment (maxer137) [reply src/mumble/MainWindow.cpp]: I added a comment; it might be a bit lengthy however.

**Review by Hartmnt — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Could you please split the two independent changes into two commits? So one for moving the close button and one for changing the settings icon.

@Hartmnt should we also backport this to 1.5?

File: src/mumble/MainWindow.cpp [hunk 2]
```diff
@@ -1666,8 +1669,14 @@ void MainWindow::on_qmServer_aboutToShow() {
 	qmServer->addAction(qaServerTokens);
 	qmServer->addAction(qaServerUserList);
 	qmServer->addAction(qaServerBanList);
+	// On macOS, the "Quit" action is automatically placed in the application menu
+	// by Qt when the QAction's menuRole is set to QAction::QuitRole (see MainWindow.ui).
+	// Adding it manually to the "Server" menu would result in duplicate entries.
+	// See GitHub issue #7151: Move the Quit button to the "Mumble" application menu on macOS.
+#ifndef Q_OS_MACOS
```
Comment (Krzmbrzl) [inline src/mumble/MainWindow.cpp]: Personal preference: I would move the comment into the `ifdef` block. But feel free to ignore, if you think this is better.

**Comment by Hartmnt** [comment]
> @Hartmnt should we also backport this to 1.5?

Nah, this will probably require resolving a merge conflict in the .ui file and I think that issue is not severe enough to bother

File: src/mumble/MainWindow.cpp (hunk 2 above)
Comment (maxer137) [reply src/mumble/MainWindow.cpp]: I think moving the comment inside makes sense. I can see both options working. I moved them inside. 👍

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.6.x|[](https://github.com/mumble-voip/mumble/pull/7157)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/mumble-voip/mumble/actions/runs/24097174978) for details
