### PR TITLE
FIX(client, audio): PulseAudio not initializing

### LINKED ISSUE #5181: PulseAudio no longer loaded
**Describe the bug**
Since commit 8aa7d9ab09b4411a1e6796659dd254628514844a initializing PulseAudio no longer works and hence it is not selectable in the Mumble settings for audio input/output. 

**Steps to Reproduce**
1. Compile Mumble on Linux, latest Git version (ce90876bf02866ea08ab66c940f0c73ba66d531a)
2. Start Mumble
3. Check if PulseAudio is enabled

**Expected behavior**
PulseAudio should be initialized properly and selectable in the Mumble settings.

**Desktop**
 - OS: Arch Linux
 - Version: Mumble-git

**Additional context**
```
$  LC_ALL=C mumble
<D>2021-07-12 20:08:30.532 PulseAudio 14.2.0 from libpulse.so
<W>2021-07-12 20:08:30.535 PulseAudio: Forcibly disconnected from PulseAudio
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<D>2021-07-12 20:08:30.551 PortAudio V19.7.0-devel, revision unknown from libportaudio.so
<X>2021-07-12 20:08:30.552 PipeWire 0.3.31 from libpipewire-0.3.so
<D>2021-07-12 20:08:30.552 JACK 1.9.18 from libjack.so
<D>2021-07-12 20:08:30.560 libopus 1.3.1 from libopus.so.0
<W>2021-07-12 20:08:30.561 CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
<W>2021-07-12 20:08:30.561 Applying fallback style sheet
<W>2021-07-12 20:08:30.561 Locale is "C" (System: "C")
<W>2021-07-12 20:08:30.561 Unable to find bundled translations for locale "C"
<W>2021-07-12 20:08:30.586 Database SQLite: "3.36.0"
<W>2021-07-12 20:08:30.596 Overlay: Listening on "/run/user/1000/MumbleOverlayPipe"
<W>2021-07-12 20:08:30.597 Updating application palette
<W>2021-07-12 20:08:30.604 GlobalShortcutX: Using XI2 2.3
<W>2021-07-12 20:08:30.616 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<W>2021-07-12 20:08:30.674 AudioInput: Opus encoder set for low delay
<W>2021-07-12 20:08:30.674 AudioInput: 128000 bits/s, 48000 hz, 480 sample
<W>2021-07-12 20:08:30.675 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2021-07-12 20:08:30.676 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2021-07-12 20:08:30.693 Zeroconf: Third-party browser API reports error -65537
<W>2021-07-12 20:08:45.365 QXcbConnection: XCB error: 3 (BadWindow), sequence: 2344, resource id: 8584451, major code: 40 (TranslateCoords), minor code: 0
```

### PR DESCRIPTION
**Pull request by Krzmbrzl**
PR #5159 removed a few seemingly unneeded waits on audio system
initialization which drastically sped up Mumble's startup. However as it
turns out for PulseAudio some waiting is actually required as the system
initializes asynchronously but we require the knowledge about the init
result.

Instead of adding an arbitrary wait time again though, this commit adds
a mechanism that waits exactly as long as necessary for the init to be
completed and then continues. That still cuts down the waiting time
tremendously when comparing with the previous (arbitrary) wait time of 1
second.

Fixes #5181

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
For me this makes PulseAudio available again

File: src/mumble/PulseAudio.cpp [hunk 1]
```diff
@@ -118,6 +118,14 @@ PulseAudioSystem::PulseAudioSystem() {
 	m_pulseAudio.threaded_mainloop_start(pam);
 
 	bRunning = true;
+
+	std::unique_lock< std::mutex > guard(m_initLock);
+	if (!m_initialized) {
+		// The mutex is atomically released as soon as this thread starts waiting and will be
+		// re-aquired when waking up.
```
Comment (davidebeatrici) [inline src/mumble/PulseAudio.cpp:125]:
```suggestion
		// re-acquired when waking up.
```

File: src/mumble/PulseAudio.cpp [hunk 2]
```diff
@@ -118,6 +118,14 @@ PulseAudioSystem::PulseAudioSystem() {
...
+		// Spurious wake-ups are avoided by checking m_initialized in the given predicate
```
Comment (davidebeatrici) [inline src/mumble/PulseAudio.cpp:126]: "predicate"? You mean "context"?

**Review by davidebeatrici — APPROVED** [review]

File: src/mumble/PulseAudio.cpp (hunk 2 above)
Comment (Krzmbrzl) [reply src/mumble/PulseAudio.cpp:126]: No - On https://en.cppreference.com/w/cpp/thread/condition_variable/wait it is called "predicate" so that is what I used here :shrug:

**Comment by radioactiveman** [comment]
> For me this makes PulseAudio available again

Confirmed, thanks for the fast response and bugfix.

**Comment by Krzmbrzl** [comment]
You're welcome - thanks for your fast reports. That makes fixing things much easier :)
