### PR TITLE
BUILD: Fix compiler warnings on 32bit architectures

### LINKED ISSUE #6377: Build error on 32-bit architecture due to missing static_casts
### Description

Build error on i386 (ia32):

1.
```
/wrkdirs/usr/ports/audio/mumble-server/work/mumble-1.5.613/src/MumbleProtocol.cpp:784:57: error: implicit conversion loses integer precision: 'std::uint64_t' (aka 'unsigned long long') to 'size_type' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
  784 |                 m_audioData.payload = gsl::span< byte >(payloadBegin, payloadSize);
      |                                       ~~~                             ^~~~~~~~~~~
```
2.
```
/wrkdirs/usr/ports/audio/mumble-server/work/mumble-1.5.613/src/murmur/Server.cpp:1044:21: error: implicit conversion changes signedness: 'int' to 'std::vector<char>::size_type' (aka 'unsigned int') [-Werror,-Wsign-conversion]
                bufVec.resize(len + 4);
                       ~~~~~~ ~~~~^~~
1 error generated.
```
3.
```
/wrkdirs/usr/ports/audio/mumble/work/mumble-1.5.613/src/mumble/Audio.cpp:46:25: error: implicit conversion loses integer precision: 'qint64' (aka 'long long') to 'long' [-Werror,-Wshorten-64-to-32]
   46 |                 long time = qetTicker.elapsed();
      |                      ~~~~   ~~~~~~~~~~^~~~~~~~~
1 error generated.
```
4.
```
/wrkdirs/usr/ports/audio/mumble/work/mumble-1.5.613/src/mumble/AudioOutput.cpp:620:16: error: implicit conversion changes signedness: 'unsigned int' to 'std::ptrdiff_t' (aka 'int') [-Werror,-Wsign-conversion]
  620 |                                                         recbuff[i] += (pfBuffer[2 * i] / 2.0f + pfBuffer[2 * i + 1] / 2.0f) * volumeAdjustment;
      |                                                         ~~~~~~~ ^
/wrkdirs/usr/ports/audio/mumble/work/mumble-1.5.613/src/mumble/AudioOutput.cpp:624:16: error: implicit conversion changes signedness: 'unsigned int' to 'std::ptrdiff_t' (aka 'int') [-Werror,-Wsign-conversion]
  624 |                                                         recbuff[i] += pfBuffer[i] * volumeAdjustment;
      |                                                         ~~~~~~~ ^
2 errors generated.
```
FreeBSD 13.2, 13.3, 14.0, 15-CURRENT (`main` branch).

### Steps to reproduce

1. Build mumble

### Mumble version

1.5.613

### Mumble component

Both

### OS

FreeBSD

### Reproducible?

Yes

### Additional information

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Krzmbrzl**
Fixes #6377

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

File: src/murmur/Server.cpp [hunk 1]
```diff
@@ -1047,7 +1047,7 @@ void Server::sendMessage(ServerUser &u, const unsigned char *data, int len, QByt
 			((reinterpret_cast< quint64 >(ebuffer.data()) + 8) & static_cast< quint64 >(~7)) + 4);
 #else
 		std::vector< char > bufVec;
-		bufVec.resize(len + 4);
+		bufVec.resize(sttaic_cast< std::size_t >(len + 4));
```
Comment (davidebeatrici) [inline src/murmur/Server.cpp:1050]:
```suggestion
		bufVec.resize(static_cast< std::size_t >(len + 4));
```

File: src/mumble/AudioOutput.cpp [hunk 2]
```diff
@@ -616,12 +616,13 @@ bool AudioOutput::mix(void *outbuff, unsigned int frameCount) {
 					if (speech->bStereo) {
 						// Mix down stereo to mono. TODO: stereo record support
 						// frame: for a stereo stream, the [LR] pair inside ...[LR]LRLRLR.... is a frame
-						for (unsigned int i = 0; i < frameCount; ++i) {
-							recbuff[i] += (pfBuffer[2 * i] / 2.0f + pfBuffer[2 * i + 1] / 2.0f) * volumeAdjustment;
+						for (std::size_t i = 0; i < frameCount; ++i) {
+							recbuff.get()[i] +=
```
Comment (davidebeatrici) [inline src/mumble/AudioOutput.cpp:620]: Why the change?

File: src/mumble/AudioOutput.cpp [hunk 3]
```diff
@@ -616,12 +616,13 @@ bool AudioOutput::mix(void *outbuff, unsigned int frameCount) {
...
+								(pfBuffer[2 * i] / 2.0f + pfBuffer[2 * i + 1] / 2.0f) * volumeAdjustment;
 						}
 					} else {
-						for (unsigned int i = 0; i < frameCount; ++i) {
-							recbuff[i] += pfBuffer[i] * volumeAdjustment;
+						for (std::size_t i = 0; i < frameCount; ++i) {
+							recbuff.get()[i] += pfBuffer[i] * volumeAdjustment;
```
Comment (davidebeatrici) [inline src/mumble/AudioOutput.cpp:625]: Same as above.

File: src/mumble/AudioOutput.cpp (hunk 2 above)
Comment (Krzmbrzl) [reply src/mumble/AudioOutput.cpp:620]: Because `recbuff` is of type `boost::shared_array` which overloads `operator[]` to take an argument of `std::ptrdiff_t` into which the compiler converts the `unsigned int` happily on x64 but produces a sign conversion warning on x86. And simply accessing the underlying buffer to use `operator[]` on that is shorter than an explicit `static_cast< std::ptrdiff_t >` :shrug:

File: src/murmur/Server.cpp (hunk 1 above)
Comment (Krzmbrzl) [reply src/murmur/Server.cpp:1050]: whoopsie ^^

File: src/mumble/AudioOutput.cpp (hunk 2 above)
Comment (davidebeatrici) [reply src/mumble/AudioOutput.cpp:620]: Makes sense.

**Review by davidebeatrici — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.5.x|[](https://github.com/mumble-voip/mumble/pull/6538)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/mumble-voip/mumble/actions/runs/10477089497) for details
