### PR TITLE
Fix and refactor problems found via GCC 7's -Wimplicit-fallthrough.

### LINKED ISSUE #3306: warning: this statement may fall through [-Wimplicit-fallthrough=]
GCC 7 throws these warnings:

```cpp
Cert.cpp: In member function ‘virtual int CertWizard::nextId() const’:
Cert.cpp:136:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
     else if (qrbExport->isChecked())
          ^~
Cert.cpp:139:3: note: here
   case 2: // Import
   ^~~~
 ```
```cpp
../Group.cpp: In static member function ‘static bool Group::isMember(Channel*, Channel*, QString, ServerUser*)’:
../Group.cpp:170:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
     maxdesc = args[2].isEmpty() ? maxdesc : args[2].toInt();
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Group.cpp:171:4: note: here
    case 2:
    ^~~~
../Group.cpp:172:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
     mindesc = args[1].isEmpty() ? mindesc : args[1].toInt();
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Group.cpp:173:4: note: here
    case 1:
    ^~~~
 ```
```cpp
Server.cpp: In member function ‘virtual void Server::run()’:
Server.cpp:851:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (bOpus)
       ^~
Server.cpp:853:6: note: here
      case MessageHandler::UDPVoiceOpus: {
      ^~~~
Server.cpp: In member function ‘void Server::message(unsigned int, const QByteArray&, ServerUser*)’:
Server.cpp:1471:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
     if (bOpus)
     ^~
Server.cpp:1473:4: note: here
    case MessageHandler::UDPVoiceOpus:
    ^~~~
```

### PR DESCRIPTION
**Pull request by davidebeatrici**
Fix and refactor problems found via GCC 7's -Wimplicit-fallthrough.

This commit fixes various problems discovered by building on Debian buster
which uses GCC 7. Building on buster gave various -Wimplicit-fallthrough warnings.

In Group.cpp and Server.cpp, we now use if statements instead of a switch with fallthrough.
This improves readability of the code, and fixes the implicit fallthroughs.

In PulseAudio.cpp, we had unintended fallthroughs in a switch statement, which have been
fixed.

In Cert.cpp, we had a potential fallthrough which was impossible to trigger at runtime,
fixed by adding an error return, like the surrounding code.

Fixes #3306.

### CODE REVIEW

File: src/Group.cpp [hunk 1]
```diff
@@ -167,9 +167,9 @@ bool Group::isMember(Channel *curChan, Channel *aclChan, QString name, ServerUse
 		switch (args.count()) {
 			default:
 			case 3:
-				maxdesc = args[2].isEmpty() ? maxdesc : args[2].toInt();
+				maxdesc = args[2].isEmpty() ? maxdesc : args[2].toInt(); // Intentional fallthrough
```
Comment (Kissaki) [inline src/Group.cpp]: I don't like it on the same line.
We're commenting non-statement control flow, not this line of code.

Comment (davidebeatrici) [reply src/Group.cpp]: Right, I'm going to move it in a new line. Do you think we should wrap the code in brackets as well?

File: src/murmur/Server.cpp [hunk 2]
```diff
@@ -849,7 +849,7 @@ void Server::run() {
 					case MessageHandler::UDPVoiceCELTAlpha:
 					case MessageHandler::UDPVoiceCELTBeta:
 						if (bOpus)
-							break;
+							break; // Intentional fallthrough
```
Comment (mkrautz) [inline src/murmur/Server.cpp]: How about this instead?

	if (msgType == MessageHandler::UDPVoiceSpeex ||
	    msgType == MessageHandler::UDPVoiceCELTAlpha ||
	    msgType == MessageHandler::UDPVoiceCELTBeta ||
	    msgType == MessageHandler::UDPVoiceOpus) {

	    // Determine if the packet should be processed
	    // by Murmur. Clients can still send non-Opus
	    // voice packets when in Opus mode. However,
	    // Murmur should discard them in that case.
	    bool ok = true;
	    if (bOpus && msgType != MessageHandler::UDPVoiceOpus) {
	   		ok = false;
	    }

	    if (ok) {
	        u->aiUdpFlag = 1;
	        processMsg(u, buffer, len);
	    }
	} else if (msgType == MessageHandler::UDPPing) {
	    QByteArray qba;
	    sendMessage(u, buffer, len, qba, true);
	}

**Comment by Kissaki** [comment]
Is it necessary to name it 'intentional fallthrough' or would the keyword 'fallthrough' be enough?

**Comment by mkrautz** [comment]
@Kissaki 
You can use 'fallthrough'.
It's a regexp match. See https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/

File: src/Group.cpp (hunk 1 above)
Comment (davidebeatrici) [reply src/Group.cpp]: Looks much better!

File: src/murmur/Server.cpp (hunk 2 above)
Comment (davidebeatrici) [reply src/murmur/Server.cpp]: It looks much better and simpler to understand, but I would use a direct statement instead of creating a variable for it.

File: src/mumble/PulseAudio.cpp [hunk 3]
```diff
@@ -268,7 +268,7 @@ void PulseAudioSystem::eventCallback(pa_mainloop_api *api, pa_defer_event *) {
 						pasInput = pa_stream_new(pacContext, "Microphone", &pss, NULL);
 						pa_stream_set_state_callback(pasInput, stream_callback, this);
 						pa_stream_set_read_callback(pasInput, read_callback, this);
-					}
+					} // Intentional fallthrough
```
[the remark this answers is not in the document]
Comment (davidebeatrici) [reply src/mumble/PulseAudio.cpp]: According to PulseAudio's [documentation](https://freedesktop.org/software/pulseaudio/doxygen/def_8h.html#a71341d6e189549fc0bd25ab669016df9), **PA_STREAM_TERMINATED** means that the stream has been terminated cleanly.

This definitely seems a like a bug, possibly correlated to #1324.

File: src/mumble/Cert.cpp [hunk 4]
```diff
@@ -135,7 +135,7 @@ int CertWizard::nextId() const {
 					return 2;
 				else if (qrbExport->isChecked())
 					return 3;
-			}
+			} // Intentional fallthrough
```
Comment (mkrautz) [inline src/mumble/Cert.cpp]: Please just add `return -1;` after the `if` block, to make the compiler happy instead.

File: src/murmur/Server.cpp [hunk 5]
```diff
@@ -844,21 +844,22 @@ void Server::run() {
...
+				if (msgType == MessageHandler::UDPVoiceSpeex ||
+					msgType == MessageHandler::UDPVoiceCELTAlpha ||
+					msgType == MessageHandler::UDPVoiceCELTBeta ||
+					msgType == MessageHandler::UDPVoiceOpus) {
+
+					// Determine if the packet should be processed
+					// by Murmur. Clients can still send non-Opus
+					// voice packets when in Opus mode. However,
+					// Murmur should discard them in that case.
+					if (bOpus && msgType != MessageHandler::UDPVoiceOpus) {
```
Comment (mkrautz) [inline src/murmur/Server.cpp]: This logic doesn't make sense? "If we're in Opus mode, only process packets that are not Opus".

File: src/murmur/Server.cpp [hunk 6]
```diff
@@ -1464,17 +1465,19 @@ void Server::message(unsigned int uiType, const QByteArray &qbaMsg, ServerUser *
...
+		if (msgType == MessageHandler::UDPVoiceSpeex ||
+			msgType == MessageHandler::UDPVoiceCELTAlpha ||
+			msgType == MessageHandler::UDPVoiceCELTBeta ||
+			msgType == MessageHandler::UDPVoiceOpus) {
+
+			// Determine if the packet should be processed
+			// by Murmur. Clients can still send non-Opus
+			// voice packets when in Opus mode. However,
+			// Murmur should discard them in that case.
+			if (bOpus && msgType != MessageHandler::UDPVoiceOpus) {
```
Comment (mkrautz) [inline src/murmur/Server.cpp]: This logic doesn't make sense? "If we're in Opus mode, only process packets that are not Opus".

File: src/murmur/Server.cpp (hunk 5 above)
Comment (mkrautz) [reply src/murmur/Server.cpp]: The reason I split it up in the first place is to make the code easier to read.

I still prefer

    bool ok = true;
    if (bOpus && msgType != MessageHandler::UDPVoiceOpus) {
   		ok = false;
    }

This (at least to me), reads:
1. Allow all packets through by default.
2. Unless we're in Opus mode. In Opus mode, only Opus packets are allowed.

So by that logic, maybe we should refactor the comment instead?

    // Allow all voice packets through by default.
    bool ok = true;
    // ...Unless we're in Opus mode. In Opus mode, only Opus packets are allowed.
    if (bOpus && msgType != MessageHandler::UDPVoiceOpus) {
   		ok = false;
    }

File: src/murmur/Server.cpp (hunk 6 above)
Comment (mkrautz) [reply src/murmur/Server.cpp]: See my previous comment.

File: src/murmur/Server.cpp (hunk 5 above)
Comment (davidebeatrici) [reply src/murmur/Server.cpp]: Oops... my fault. I read the inverted logic.

File: src/mumble/Cert.cpp [hunk 7]
```diff
@@ -135,6 +135,8 @@ int CertWizard::nextId() const {
 					return 2;
 				else if (qrbExport->isChecked())
 					return 3;
+
```
Comment (mkrautz) [inline src/mumble/Cert.cpp]: To match the style here, drop this newline.

File: src/murmur/Server.cpp [hunk 8]
```diff
@@ -1464,17 +1468,22 @@ void Server::message(unsigned int uiType, const QByteArray &qbaMsg, ServerUser *
...
-			case MessageHandler::UDPVoiceSpeex:
-				if (bOpus)
-					break;
-			case MessageHandler::UDPVoiceOpus:
-				processMsg(u, buffer, l);
-				break;
-			default:
-				break;
+		if (msgType == MessageHandler::UDPVoiceSpeex ||
+			msgType == MessageHandler::UDPVoiceCELTAlpha ||
```
Comment (mkrautz) [inline src/murmur/Server.cpp]: Please use spaces for alignment, and align msgType with the first line:

    if (msgType == MessageHandler::UDPVoiceSpeex ||
        msgType == MessageHandler::UDPVoiceCELTAlpha ||
        [...]

File: src/murmur/Server.cpp [hunk 9]
```diff
@@ -844,21 +844,25 @@ void Server::run() {
...
-							u->aiUdpFlag = 1;
-							processMsg(u, buffer, len);
-							break;
-						}
-					case MessageHandler::UDPPing: {
-							QByteArray qba;
-							sendMessage(u, buffer, len, qba, true);
-						}
+				if (msgType == MessageHandler::UDPVoiceSpeex ||
+					msgType == MessageHandler::UDPVoiceCELTAlpha ||
```
Comment (mkrautz) [inline src/murmur/Server.cpp]: Ditto.

**Comment by mkrautz** [comment]
Maybe you should fix the commit message/title?

How about:

    Fix and refactor problems found via GCC 7's -Wimplicit-fallthrough.
    
    This commit fixes various problems discovered by building on Debian buster
    which uses GCC 7. Building on buster gave various -Wimplicit-fallthrough warnings.

    In Group.cpp and Server.cpp, we now use if statements instead of a switch with fallthrough.
    This improves readability of the code, and fixes the implicit fallthroughs.

    In PulseAudio.cpp, we had unintended fallthroughs in a switch statement, which have been
    fixed.

    In Cert.cpp, we had a potential fallthrough which was impossible to trigger at runtime,
    fixed by adding an error return, like the surrounding code.

**Comment by davidebeatrici** [comment]
Don't ask why I pasted the wrong sentence...

**Comment by mkrautz** [comment]
Please also fix PR title/message. That's what we use when landing.

**Comment by davidebeatrici** [comment]
Done.

**Comment by mkrautz** [comment]
LGTM. Let's wait for CI to finish before landing.

**Comment by hacst** [comment]
Kinda late to the party. Sorry. If we ever actually introduce any fallthrough annotation we should probably see about using https://doc-snapshots.qt.io/qt5-dev/qtglobal.html#Q_FALLTHROUGH . It will define to C++17 [[fallthrough]] on capable compilers going forwards meaning it should just work (TM) with any compiler or linter. Ofc needs a legacy define.

W.r.t to the PR @mkrautz where did the ```u->aiUdpFlag = 1;``` come from? That wasn't there before. Also are you sure the PA fallthrough was a bug? Because "try re-starting our output until we no longer want to output (as in pao is gone)" even if the stream was closed cleanly for some reason kinda made enough sense to me to not touch it when I stumbled over those fallthrough it in the past. Now said that I have no clue about pulse audio so it is quite possible I just managed to explain away an actual bug....

**Comment by davidebeatrici** [comment]
> Kinda late to the party. Sorry. If we ever actually introduce any fallthrough annotation we should probably see about using https://doc-snapshots.qt.io/qt5-dev/qtglobal.html#Q_FALLTHROUGH . It will define to C++17 [[fallthrough]] on capable compilers going forwards meaning it should just work (TM) with any compiler or linter. Ofc needs a legacy define.

If we ship Mumble 1.3.x with Qt 5 support only, we can avoid defining `Q_FALLTHROUGH` manually, as it is introduced in Qt 5.8.

Qt 5.9 is the latest LTS release, meaning that it should be available on most up-to-date distros.

> W.r.t to the PR @mkrautz where did the u->aiUdpFlag = 1; come from? That wasn't there before.

My fault, I copied both lines from the previous part of code without noticing that `u->aiUdpFlag=1` was present only there.

> Also are you sure the PA fallthrough was a bug? Because "try re-starting our output until we no longer want to output (as in pao is gone)" even if the stream was closed cleanly for some reason kinda made enough sense to me to not touch it when I stumbled over those fallthrough it in the past. Now said that I have no clue about pulse audio so it is quite possible I just managed to explain away an actual bug...

The main problem in the code is that the switch-case block is wrong, in my opinion.
According to [PulseAudio's documentation ](https://freedesktop.org/software/pulseaudio/doxygen/def_8h.html#a71341d6e189549fc0bd25ab669016df9), `PA_STREAM_TERMINATED` indicates that the stream has been terminated cleanly, meaning that we shouldn't initialize the stream there.

We even manually set that state in case the stream is not initialized yet: https://github.com/mumble-voip/mumble/blob/1b203cdc8becf8d273feb285240db2f27ffa261b/src/mumble/PulseAudio.cpp#L180

After multiple debugging sessions, I can safely say that this is related to AudioOutput failing when switching from PulseAudio to ALSA and then back to PulseAudio.

But the major problem right now is that Mumble, when using PulseAudio, messes with the global audio output, making it very, very bad.

Proper sound can be restored by changing the volume level system-wise, but the quality is still lower than ALSA.

**Comment by mkrautz** [comment]
@davidebeatrici I agree with hacst. The fallthroughs in Pulse are probably intentional.
Please revert the changes in there by replacing `break` with `// Fallthrough`.

**Comment by davidebeatrici** [comment]
Should I also revert this in the same PR?

https://github.com/mumble-voip/mumble/blob/1b203cdc8becf8d273feb285240db2f27ffa261b/src/murmur/Server.cpp#L1484

**Comment by mkrautz** [comment]
You can do a fixup PR and fix both of them in separate commits.

**Comment by Athernar** [comment]
Something in this recent string of commits broke mumbledj playback, mumbledj appears to be operating correctly (python and ffmpeg subprocesses spawn and terminate as expected) but no transmission is seen from the bot in mumble itself. Reverting murmur to an earlier commit restores functionality.

Granted mumbledj is unmaintained abandonware, but I thought I'd just mention it in case this issue goes beyond effecting mumbledj.

**Comment by mkrautz** [comment]
@Athernar Have you tested with https://github.com/mumble-voip/mumble/commit/1273ba90b65f76d0a3fa450893df9a025fee519e applied? (It's landed, so current git master)

**Comment by Athernar** [comment]
Yup, was broken both before and after that commit. Just rebuilt murmur to make sure too, broke output.
