### PR TITLE
FIX(client,mac): Add support for input/output device switching on macOS

### LINKED ISSUE #1013: Mumble does not detect changes in default audio devices while running
I use Mac OS X 10.8.4 and in Mumble I have set the audio input and audio output to "Default Device". Yet switching an audio input or output device in the system has no effect on Mumble. Mumble always sticks to the audio device that was set in the system when Mumble started running. Mumble never changes audio devices automatically when they are changed in the system settings. In order to change an audio device in Mumble I either have to set it manually or quit Mumble and start it again after selecting the audio device in the system.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1013/ ._

### PR DESCRIPTION
**Pull request by jlsalmon**
Previously, when switching input/output devices at the system level, Mumble would ignore the switch and continue to use the previous device. This patch adds support for proper device switching, allowing Mumble to correctly follow the system input/output device.

Fixes #1013

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

File: src/mumble/CoreAudio.mm [hunk 1]
```diff
@@ -1108,3 +1115,20 @@ static void LogAUStreamDescription(AudioUnit au) {
...
+	Q_UNUSED(inNumberAddresses);
+	Q_UNUSED(inAddresses);
+
+	CoreAudioOutput *o = reinterpret_cast< CoreAudioOutput * >(udata);
+	if (!o->bRunning) return noErr;
+
+	qWarning("CoreAudioOutput: Output device change detected. Restarting AudioOutput.");
+	o->stop();
+	Audio::stopOutput();
+	Audio::startOutput();
```
Comment (Krzmbrzl) [inline src/mumble/CoreAudio.mm:1131]: Did you check whether explicitly calling `o->stop()` is required? It seems like `Audio::stopOutput()` should already take care of that :thinking:

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
Please run `clang-format` on the changed files (at least the header file - not sure if it even works on the `.mm` one) or alternatively run `scripts/runClangFormat.sh` which should invoke clang-format on all files.

**Comment by Krzmbrzl** [comment]
Thanks for tackling this! I am wondering though whether it might be more appropriate to label this as a fix rather than a new feature. I guess it would be the expected behavior for such changes to be picked up and thus it not doing so seems more like a bug to me... What do you think? :thinking: 

> Note that this does not cover input device switching, but in theory the solution for that should be similar to this. I'd be happy to add input device switching support as well, if requested.

Absolutely! I think this would even be well suited to be done in one and the same commit :+1:

**Comment by jlsalmon** [comment]
I agree, it does seem like this should be something that "just works" so a fix is probably more appropriate. I'll rework this as a fix, and implement the input device switching at the same time later today 👍

File: src/mumble/CoreAudio.mm (hunk 1 above)
Comment (jlsalmon) [reply src/mumble/CoreAudio.mm:1131]: I didn't actually check that, no - I'll see what happens if it's removed

Comment (jlsalmon) [reply src/mumble/CoreAudio.mm]: You're right, it wasn't required - removed 👍

**Comment by jlsalmon** [comment]
Ok, input switching implemented, tested and working great with a bunch of different device switches (bluetooth headphones, AirPods, USB headset, internal microphone). 

Had to manually fiddle with the .mm file formatting, but I'm fairly sure it's OK now. 

Question about versioning: I see that there's a `1.4.x` maintenance branch but not a `1.3.x` branch - does that mean that master is tracking `1.3.x`? If so, does that mean that this would make it into the next 1.3 release if accepted?

**Comment by Krzmbrzl** [comment]
Nice! :+1: 

> Question about versioning: I see that there's a 1.4.x maintenance branch but not a 1.3.x branch - does that mean that master is tracking 1.3.x? If so, does that mean that this would make it into the next 1.3 release if accepted?

Current master is tracking 1.5.0. However this fix will then be backported to the 1.4.x branch to still make it into the upcoming release of 1.4.0. There will be no further 1.3.x releases since 1.4.0 is very close to being finished :point_up:

**Review by Krzmbrzl — APPROVED** [review]

**Comment by jlsalmon** [comment]
Awesome, thanks @Krzmbrzl, looking forward to seeing this in 1.4.0 :)

**Comment by Krzmbrzl** [comment]
Thanks for fixing this! :+1:
