### PR TITLE
GlobalShortcutMac: fix segmentation fault in setEnabled()

### LINKED ISSUE #3471: macOS Mojave: passing the null port to CGEventTapEnable() segfaults
Trying to run Mumble-1.3.0\~2729\~g2126495~snapshot.dmg and the latest stable release on macOS 10.14 Beta (18A326h). Mumble icon loads and then crashes. Restarting the app gives you the option to send crash report, but when I do that it dies again and says:

"This really isn't funny, but apparently there's a bug in the crash reporting code, and we've failed to upload the report. You may inform a developer about error 401".

<details>

 <summary>osx logs</summary>

```
Process:               Mumble [69266]
Path:                  /Applications/Mumble.app/Contents/MacOS/Mumble
Identifier:            net.sourceforge.mumble.Mumble
Version:               1.3.0~2729~g2126495~snapshot
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Mumble [69266]
User ID:               501

Date/Time:             2018-07-16 22:29:00.502 +0200
OS Version:            Mac OS X 10.14 (18A326h)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)
Anonymous UUID:        9BFEE1B3-56D9-9ECE-0F60-128ACDAAB2C9

Sleep/Wake UUID:       4BE1F946-A94C-4AAA-84B2-BDFD28C123B0

Time Awake Since Boot: 190000 seconds
Time Since Wake:       120000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000038
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [69266]

VM Regions Near 0x38:
--> 
    __TEXT                 00000001031a6000-00000001052f8000 [ 33.3M] r-x/rwx SM=COW  /Applications/Mumble.app/Contents/MacOS/Mumble

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff40e4136c CFMachPortGetContext + 4
1   com.apple.SkyLight            	0x00007fff66e6a0f1 SLEventTapEnable + 49
2   net.sourceforge.mumble.Mumble 	0x00000001033422da GlobalShortcut::GlobalShortcut(QObject*, int, QString, QVariant) + 202
3   net.sourceforge.mumble.Mumble 	0x000000010321b24f MainWindow::createActions() + 111
4   net.sourceforge.mumble.Mumble 	0x000000010321a7c6 MainWindow::MainWindow(QWidget*) + 2326
5   net.sourceforge.mumble.Mumble 	0x0000000103211bbc main + 9036
6   net.sourceforge.mumble.Mumble 	0x00000001031ae634 start + 52

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff6de7a30c start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 2:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff6dddfb92 __select + 10
1   com.apple.CoreFoundation      	0x00007fff40e59eae __CFSocketManager + 639
2   libsystem_pthread.dylib       	0x00007fff6de7a7fe _pthread_body + 128
3   libsystem_pthread.dylib       	0x00007fff6de7a76a _pthread_start + 70
4   libsystem_pthread.dylib       	0x00007fff6de7a329 thread_start + 13

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6ddd5a96 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6ddd4f9c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff40e28d11 __CFRunLoopServiceMachPort + 337
3   com.apple.CoreFoundation      	0x00007fff40e281af __CFRunLoopRun + 1654
4   com.apple.CoreFoundation      	0x00007fff40e27921 CFRunLoopRunSpecific + 463
5   com.apple.AppKit              	0x00007fff3e4de1ef _NSEventThread + 160
6   libsystem_pthread.dylib       	0x00007fff6de7a7fe _pthread_body + 128
7   libsystem_pthread.dylib       	0x00007fff6de7a76a _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff6de7a329 thread_start + 13

Thread 4:: Qt HTTP thread
0   libsystem_kernel.dylib        	0x00007fff6dddf83e __pselect + 10
1   libsystem_kernel.dylib        	0x00007fff6dddb39f pselect$1050 + 82
2   net.sourceforge.mumble.Mumble 	0x00000001045c9ba7 qt_safe_select(int, fd_set*, fd_set*, fd_set*, timespec const*) + 103
3   net.sourceforge.mumble.Mumble 	0x00000001045cac95 QEventDispatcherUNIXPrivate::doSelect(QFlags<QEventLoop::ProcessEventsFlag>, timespec*) + 709
4   net.sourceforge.mumble.Mumble 	0x00000001045cc0d7 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 231
5   net.sourceforge.mumble.Mumble 	0x000000010456f9a1 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 417
6   net.sourceforge.mumble.Mumble 	0x00000001043b60a3 QThread::exec() + 115
7   net.sourceforge.mumble.Mumble 	0x00000001043b9b4a QThreadPrivate::start(void*) + 362
8   libsystem_pthread.dylib       	0x00007fff6de7a7fe _pthread_body + 128
9   libsystem_pthread.dylib       	0x00007fff6de7a76a _pthread_start + 70
10  libsystem_pthread.dylib       	0x00007fff6de7a329 thread_start + 13

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff6de7a30c start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff6de7a30c start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff6de7a30c start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6de7a30c start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6de7a30c start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff6de7a30c start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 11:
0   libsystem_pthread.dylib       	0x00007fff6de7a30c start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x53cfce9fabe9000a  rbx: 0x00007ffeeca58cc8  rcx: 0x00000001033b19b0  rdx: 0x00007fe81a824200
  rdi: 0x0000000000000000  rsi: 0x00007ffeeca58cc8  rbp: 0x00007ffeeca58cb0  rsp: 0x00007ffeeca58cb0
   r8: 0x000000000000004d   r9: 0x00000000000007fb  r10: 0x00007ffeeca59c88  r11: 0x00007fff66e6a0c0
  r12: 0x000060000192a2d8  r13: 0x000060000192a2e0  r14: 0x0000000000000001  r15: 0x00007ffeeca59010
  rip: 0x00007fff40e4136c  rfl: 0x0000000000010206  cr2: 0x0000000000000038
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x1031a6000 -        0x1052f7acf +net.sourceforge.mumble.Mumble (1.3.0~2729~g2126495~snapshot) <193EFF41-156F-376C-96CD-B1C8038D7292> /Applications/Mumble.app/Contents/MacOS/Mumble
       0x109ff8000 -        0x10a13fff7  com.apple.AMDMTLBronzeDriver (2.0.18 - 2.0.0) <B042B112-59D6-3D9E-8F09-ED7E31276CD7> /System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/AMDMTLBronzeDriver
       0x10a994000 -        0x10a9abfff +libcelt0.0.7.0.dylib (0.7) <496B31E4-C928-37E5-9EE0-90AB8B5853FC> /Applications/Mumble.app/Contents/Codecs/libcelt0.0.7.0.dylib
       0x10a9b1000 -        0x10a9cdfff +libcelt0.0.11.0.dylib (0.11) <1F4DF6FC-7F4F-35DD-B95D-E1605C250660> /Applications/Mumble.app/Contents/Codecs/libcelt0.0.11.0.dylib
       0x113ee5000 -        0x113f63647  dyld (623.1) <49FBACEF-4076-3808-ABC9-A90D583435F6> /usr/lib/dyld
    0x7fff3b409000 -     0x7fff3b657ff7  com.apple.driver.AppleIntelSKLGraphicsMTLDriver (12.0.15 - 12.0.0) <80568C51-CBDA-32CB-9E2B-E0B8C4A702FB> /System/Library/Extensions/AppleIntelSKLGraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelSKLGraphicsMTLDriver
    0x7fff3cce5000 -     0x7fff3cce9fff  com.apple.agl (3.3.2 - AGL-3.3.2) <6144D744-D918-36A5-88E9-9CD1312C7A0A> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff3d134000 -     0x7fff3d134fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <1074FD23-5FE0-333C-A9A2-88E2289C28DC> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff3d135000 -     0x7fff3d14bfe3  libCGInterfaces.dylib (506.18) <BA2F4B33-9797-39C4-AF7F-11E22DA2BA34> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff3d14c000 -     0x7fff3d7ecfe7  com.apple.vImage (8.1 - ???) <03A80D88-BB5B-33A5-9162-BDB4275BA959> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff3d7ed000 -     0x7fff3da64fc7  libBLAS.dylib (1243.200.4) <A62EFB15-C0DB-38AE-AF12-59A20FACCF2F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff3da65000 -     0x7fff3dad7fe7  libBNNS.dylib (38.200.2) <C326EC48-E714-3B84-B432-174C1E115145> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff3dad8000 -     0x7fff3de7eff7  libLAPACK.dylib (1243.200.4) <FC99AAA1-A7DF-3773-B1A6-A59C9501ED71> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff3de7f000 -     0x7fff3de94ffb  libLinearAlgebra.dylib (1243.200.4) <D67DD4E2-BD62-3B66-8C2C-631247135404> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff3de95000 -     0x7fff3de9aff3  libQuadrature.dylib (3.200.2) <A81CE5F7-8F37-3F6B-BC74-22730C230C61> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff3de9b000 -     0x7fff3df18ffb  libSparse.dylib (79.200.4) <1DEEFAEC-7788-3AF2-BAB2-33EC96926772> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff3df19000 -     0x7fff3df2cffb  libSparseBLAS.dylib (1243.200.4) <FC86E07E-134E-31C9-81A9-8E858CC1894D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff3df2d000 -     0x7fff3e114fcf  libvDSP.dylib (671.200.20) <1DE3D255-11A7-3FDA-AA82-28801BAD06A2> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff3e115000 -     0x7fff3e1caff7  libvMisc.dylib (671.200.20) <A712052C-00F8-3936-95D0-90E7C3478C38> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff3e1cb000 -     0x7fff3e1cbfff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <BA9EE9F6-72A4-3976-A578-60DC86B73BCF> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff3e377000 -     0x7fff3f174ffb  com.apple.AppKit (6.9 - 1643.10.101) <8B495466-664D-3A15-9E44-14B8A19B7212> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3f1c6000 -     0x7fff3f1c6fff  com.apple.ApplicationServices (48 - 50) <02EE7158-2E29-3B00-8B51-3D659A2DD50C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff3f1c7000 -     0x7fff3f232ff7  com.apple.ApplicationServices.ATS (377 - 453.8) <F94C7953-70DA-3015-A97B-5FD49A8214DC> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff3f2cb000 -     0x7fff3f3eafff  libFontParser.dylib (228.5) <E36091EB-E63F-39C9-A9B0-E40E351CAEFC> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fff3f3eb000 -     0x7fff3f436fff  libFontRegistry.dylib (228.8) <AE3A9562-C04A-3909-A60F-D315F318A15F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff3f494000 -     0x7fff3f4c7ff7  libTrueTypeScaler.dylib (228.5) <DC10713C-2428-3A13-87D3-A12B58CC6016> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fff3f532000 -     0x7fff3f536ff3  com.apple.ColorSyncLegacy (4.13.0 - 1) <CAE1257E-7794-357E-AAE0-FF5BF9CA3944> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff3f5d3000 -     0x7fff3f625fff  com.apple.HIServices (1.22 - 627.14) <1D5EB73F-8606-3C0F-929C-8EAABD1B80C8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff3f626000 -     0x7fff3f634ff3  com.apple.LangAnalysis (1.7.0 - 1.7.0) <6E9923F1-EC4B-3084-AEEF-EB047FE75607> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff3f635000 -     0x7fff3f681fff  com.apple.print.framework.PrintCore (14.0 - 503.5) <F43B03A8-DEF7-3D3D-9006-5EC513D1E5EA> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff3f682000 -     0x7fff3f6bdff7  com.apple.QD (3.12 - 407) <C9EFD820-B9E3-3301-9C61-F146FBD9BD18> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff3f6be000 -     0x7fff3f6caff7  com.apple.speech.synthesis.framework (8.0.10 - 8.0.10) <72736CCA-F607-3FAD-8915-831E18687E97> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff3f6cb000 -     0x7fff3f959ff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <6DC14AF5-F919-3A98-9A54-CBD843F9FD3F> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff3f95b000 -     0x7fff3f95bfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <B90634A9-3353-3C66-86DC-6520941298DA> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff3fcba000 -     0x7fff40079ff7  com.apple.CFNetwork (958.1 - 958.1) <2768A2C1-ED2E-3F87-9586-BA0A21EBAB5C> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff4008e000 -     0x7fff4008efff  com.apple.Carbon (158 - 158) <B24A5EEA-E1E2-3C28-ADDB-3EF56422006D> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff4008f000 -     0x7fff40092ffb  com.apple.CommonPanels (1.2.6 - 98) <93C32399-3383-35F6-A921-1F6596E923D7> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff40093000 -     0x7fff4039afff  com.apple.HIToolbox (2.1.1 - 916.21) <074665E5-6F97-3DAA-B3BE-D5CC12A8EBFC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff4039b000 -     0x7fff4039effb  com.apple.help (1.3.8 - 66) <DA38A437-0635-3E9B-B354-26E47401152E> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff4039f000 -     0x7fff403a4ff7  com.apple.ImageCapture (9.0 - 1521) <99219A86-9416-35CB-9BCC-256B0B50FE18> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff403a5000 -     0x7fff40439ffb  com.apple.ink.framework (10.9 - 222) <72BDCD9F-A284-3BAA-8AD0-710570EC23DD> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff4043a000 -     0x7fff40454ff7  com.apple.openscripting (1.7 - 176) <5C4B5749-21AA-3A18-8EAC-AD503E6F9E7E> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff40475000 -     0x7fff40476fff  com.apple.print.framework.Print (14.0 - 267.3) <F751FA61-4053-369A-B9BA-FED72192D58E> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff40477000 -     0x7fff40479ff7  com.apple.securityhi (9.0 - 55006) <0062DB40-6D1F-30B7-A68F-D4E8D993B597> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff4047a000 -     0x7fff40480ff7  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <46BF17E6-AD1F-3A92-8180-7F06F95800E9> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff405a7000 -     0x7fff405a7fff  com.apple.Cocoa (6.11 - 23) <BE97D6EC-3C76-3425-8667-8D2E0AB68058> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff405b5000 -     0x7fff40681fff  com.apple.ColorSync (4.13.0 - 3334) <4A60884B-5F5E-3F4F-A17C-B0B07976A17E> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff40817000 -     0x7fff408a7fff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <5873EC1A-9732-3C45-8752-9D063E6C98B6> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff4090d000 -     0x7fff40938ffb  com.apple.CoreBluetooth (1.0 - 1) <BC8A9068-D45E-3778-BCC1-4DA45F284091> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff40939000 -     0x7fff40cd5fef  com.apple.CoreData (120 - 864.1) <33DBFDE2-D39E-37B3-83CA-F6FCDA00551A> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff40cd6000 -     0x7fff40dbcff7  com.apple.CoreDisplay (101.3 - 101.3) <99336868-1633-3A58-B5AF-FF5DD78B8A9F> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff40dbd000 -     0x7fff4120afef  com.apple.CoreFoundation (6.9 - 1542.11) <C0A1C7A3-526E-3E17-8B30-220BD77123EE> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4120c000 -     0x7fff41895fff  com.apple.CoreGraphics (2.0 - 1232) <625D3477-63F3-393C-9877-603A4E596BD7> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff41897000 -     0x7fff41b8ffff  com.apple.CoreImage (14.0.0 - 650.1) <8F0BE7B1-08BB-3367-B341-52B630C6C959> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff420e2000 -     0x7fff420e2fff  com.apple.CoreServices (925.2 - 925.2) <0C53490C-8AC2-350C-A391-D9F8DFAF7294> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff420e3000 -     0x7fff4215bfff  com.apple.AE (758.1 - 758.1) <F026304E-777A-335A-AA39-98B0759FED9F> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff4215c000 -     0x7fff42433fff  com.apple.CoreServices.CarbonCore (1178.8 - 1178.8) <0A8F4386-E26D-3A38-80B2-8BF2B3429E94> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff42434000 -     0x7fff4247efff  com.apple.DictionaryServices (1.2 - 284.15.3) <F32E8AE3-1FE1-3826-85DC-E751882A830F> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff4247f000 -     0x7fff42487ff3  com.apple.CoreServices.FSEvents (1239.200.11 - 1239.200.11) <8579F716-5F75-3335-9DEC-67564BF136F4> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff42488000 -     0x7fff4264efff  com.apple.LaunchServices (925.2 - 925.2) <4F3333A7-59DB-3308-B33F-B118DB7399F4> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff4264f000 -     0x7fff426f1ff3  com.apple.Metadata (10.7.0 - 1191.31) <EF7088A5-456E-32C7-929E-2EF68810423F> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff426f2000 -     0x7fff4273eff7  com.apple.CoreServices.OSServices (925.2 - 925.2) <267F9083-D9A1-3DA0-9CC0-990BB671C842> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff4273f000 -     0x7fff427adff7  com.apple.SearchKit (1.4.0 - 1.4.0) <4BE43EE2-544E-3812-A26A-01429BFD960A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff427ae000 -     0x7fff427d2ff7  com.apple.coreservices.SharedFileList (71.26 - 71.26) <C04013B6-AE2B-3FE4-AE09-00C057E1B994> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff42b0c000 -     0x7fff42c6bff3  com.apple.CoreText (352.0 - 584.16.1.1) <BC685657-6E40-3C92-8DC6-0CB72B96A6D2> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff42c6c000 -     0x7fff42cc2ffb  com.apple.OTSVG (1.0 - ???) <C67510D5-94C7-35FB-A2B6-E7699685C4BC> /System/Library/Frameworks/CoreText.framework/Versions/A/Frameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff42cc3000 -     0x7fff42d00ff3  com.apple.CoreVideo (1.8 - 0.0) <C7AAAA31-F8E1-3D20-B3A7-0765B19D4139> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff42d01000 -     0x7fff42d97fff  com.apple.framework.CoreWLAN (13.0 - 1370.6) <1473D2E3-4E41-31AC-A957-C02379DE54EA> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff43015000 -     0x7fff4301afff  com.apple.DiskArbitration (2.7 - 2.7) <975B3209-AB83-3311-8A50-5065E7FE7478> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff431de000 -     0x7fff435adffb  com.apple.Foundation (6.9 - 1542.11) <870EBCF1-2431-3FA6-8A8A-352B9778A2E3> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff4361e000 -     0x7fff4364efff  com.apple.GSS (4.0 - 2.0) <F26D27B7-544D-3E1A-99A4-9FD9665AF10B> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff43767000 -     0x7fff43870ff7  com.apple.Bluetooth (6.0.8 - 6.0.8d27) <0696964F-0AAC-3D65-9260-68206F133E14> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff438d2000 -     0x7fff43962ff7  com.apple.framework.IOKit (2.0.2 - 1483.200.46) <6F445C86-E9AA-3E08-AD9E-3FFC54F00A44> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff43964000 -     0x7fff4396eff7  com.apple.IOSurface (251 - 251) <68D0BB00-449F-305F-AF16-CACFA37ABEE0> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff439c5000 -     0x7fff43b57ff7  com.apple.ImageIO.framework (3.3.0 - 1787) <952DAB7A-4EB7-3D50-A26C-F24E743E7245> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff43b58000 -     0x7fff43b5cffb  libGIF.dylib (1787) <CE78B68E-542D-32CA-81B3-0EC471AAAFE5> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff43b5d000 -     0x7fff43c43fff  libJP2.dylib (1787) <4E977D26-BD9B-3FD7-8A6D-65C17F92E69C> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff43c44000 -     0x7fff43c69ff7  libJPEG.dylib (1787) <2FB55A58-703F-341C-8901-2224E27D713D> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff43f3c000 -     0x7fff43f62fe7  libPng.dylib (1787) <E42EA0CC-AF4D-396E-818C-50301F3FBDFB> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff43f63000 -     0x7fff43f65ff7  libRadiance.dylib (1787) <221C2DFA-CA8D-37A2-8A40-F09AC3DC1FEF> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff43f66000 -     0x7fff43fb4ffb  libTIFF.dylib (1787) <77CC99EB-2BD7-3F8C-B8B1-9031C5AB10A7> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff4507f000 -     0x7fff45098fff  com.apple.Kerberos (3.0 - 1) <250A186C-E44C-3C3A-8B13-7DE3D5A8573A> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff45ec2000 -     0x7fff45f54ff7  com.apple.Metal (157.38.1 - 157.38.1) <AAC73FE8-1C12-3DCA-B70C-9AC6CA6B42EC> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff45f71000 -     0x7fff45f90fff  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <C7F27F09-069E-33D4-B268-CD1D70C184EF> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff45f91000 -     0x7fff4600efe7  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <92DB36AE-6746-320B-A026-53119087D133> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff4600f000 -     0x7fff46037ff7  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <7CB45224-36C6-308A-87A8-0A00F2BD35B7> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff46038000 -     0x7fff4615cfff  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <F01D04B5-32C4-3060-90DE-D1AB1E24B5F1> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff4615d000 -     0x7fff4617bff7  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <A3D65564-C1B9-3FF3-8880-F6697C561D1F> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff4617c000 -     0x7fff4617cff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <C96631FD-34D1-307D-9EE6-2F358184DFB6> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff47348000 -     0x7fff47354fff  com.apple.NetFS (6.0 - 4.0) <062097EC-AC63-37E1-923A-2827A89C2827> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff49e14000 -     0x7fff49e6dff7  com.apple.opencl (2.12.1 - 2.12.1) <F481456A-0934-38B7-8D43-64CCAFC27149> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff49e6e000 -     0x7fff49e8aff3  com.apple.CFOpenDirectory (10.14 - 207.200.3) <8CBFACF8-BD74-3966-833F-78A8758CE7CD> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff49e8b000 -     0x7fff49e97ff7  com.apple.OpenDirectory (10.14 - 207.200.3) <8AB88A6F-2D5D-35BE-ABFE-76E05F7EED62> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff4a7fb000 -     0x7fff4a7fdfff  libCVMSPluginSupport.dylib (17.0.31) <BC96A65E-FA17-3A6A-9DA6-63841B2D6D1B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff4a7fe000 -     0x7fff4a803ff3  libCoreFSCache.dylib (163.17.1) <EAC21387-596E-385F-8180-6BE142AD1802> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff4a804000 -     0x7fff4a808fff  libCoreVMClient.dylib (163.17.1) <F39629DA-1821-325E-8C75-B36C60B9F195> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff4a809000 -     0x7fff4a811ffb  libGFXShared.dylib (17.0.31) <1063AD81-CE6A-38C4-BF54-8142BD788C74> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff4a812000 -     0x7fff4a81dfff  libGL.dylib (17.0.31) <4F66D3EF-3875-3143-8B57-59542445326F> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff4a81e000 -     0x7fff4a858fef  libGLImage.dylib (17.0.31) <11CF069A-E9E1-3BBB-BCED-3925330DC254> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff4a9cd000 -     0x7fff4aa0afff  libGLU.dylib (17.0.31) <984826B8-5D7F-321A-86E5-FB2561EA8FDF> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff4b3bc000 -     0x7fff4b3cbff3  com.apple.opengl (17.0.31 - 17.0.31) <59EB0C7C-94B2-3664-A76A-172C2BC321CB> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff4c21b000 -     0x7fff4c493fff  com.apple.QuartzCore (1.11 - 681.62) <3684877D-B094-3219-B347-75954A3FC1C4> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff4ccbf000 -     0x7fff4ccd7ff7  com.apple.ScriptingBridge (1.4 - 75) <B9159EFB-5C52-3420-BBA3-0D85D7C06E42> /System/Library/Frameworks/ScriptingBridge.framework/Versions/A/ScriptingBridge
    0x7fff4ccd8000 -     0x7fff4cffdfff  com.apple.security (7.0 - 58286.200.178) <34455E29-DCE7-3A27-9C20-A90870D0B372> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff4cffe000 -     0x7fff4d08dfff  com.apple.securityfoundation (6.0 - 55185.200.14) <EEC9CBB2-8B86-34AE-B64F-FA347349706E> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff4d08e000 -     0x7fff4d0befff  com.apple.securityinterface (10.0 - 55109.200.6) <5D5F9375-8ECA-30DB-8D12-F41303FC1889> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff4d0bf000 -     0x7fff4d0c3ffb  com.apple.xpc.ServiceManagement (1.0 - 1) <0E996536-90F7-3030-8514-9A4D391C80D9> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff4d480000 -     0x7fff4d4f0ff7  com.apple.SystemConfiguration (1.17 - 1.17) <DFD4A8AC-CD5B-385E-878D-5E522EAA0381> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff50784000 -     0x7fff50828ff7  com.apple.APFS (1.0 - 1) <F6629C8A-1A21-34AA-8554-0670D81CC163> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff51235000 -     0x7fff51236ff3  com.apple.AggregateDictionary (1.0 - 1) <F2FCA909-C985-38EF-972B-A60757B0BAC2> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff5182e000 -     0x7fff5185aff7  com.apple.framework.Apple80211 (13.0 - 1375.9) <9288BBAA-B874-304F-B9BD-D89284F61AAD> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff51b34000 -     0x7fff51b43ff7  com.apple.AppleFSCompression (96.200.2 - 1.0) <BB890E07-810D-341F-B551-EACECB60DD55> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff51c40000 -     0x7fff51c4bfff  com.apple.AppleIDAuthSupport (1.0 - 1) <ADA3B339-FCD6-335B-9E05-0E29BE934254> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff51c8c000 -     0x7fff51cd5fff  com.apple.AppleJPEG (1.0 - 1) <E82E8F53-CD12-3721-9E6A-F5FCAE3090C4> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff51f1a000 -     0x7fff51f42ff7  com.apple.applesauce (1.0 - ???) <825CCD7C-3B3F-3D2C-8EE0-5DC2755F5BB1> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff520a7000 -     0x7fff520bdffb  com.apple.AssertionServices (1.0 - 1) <01864DD9-F7BC-316F-B601-8BD423576F08> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff523d7000 -     0x7fff52674fff  com.apple.AuthKit (1.0 - 1) <C4F8C4F8-117A-3636-9442-CBE8A565B3B9> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff52842000 -     0x7fff52849fff  com.apple.coreservices.BackgroundTaskManagement (1.0 - 57.1) <D4275823-016A-36FE-A8E1-E73F8D4D7BC1> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff5284a000 -     0x7fff528daff7  com.apple.backup.framework (1.10 - ???) <9AF9A530-BD18-33C9-8CB6-244B152DF303> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff528db000 -     0x7fff5294cffb  com.apple.BaseBoard (360.17 - 360.17) <CF3BF411-426A-35E1-B2F1-FE2927221567> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff544e3000 -     0x7fff544ecfff  com.apple.CommonAuth (4.0 - 2.0) <79EEAA3F-6866-3E03-AF4B-4B853C11B52A> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff550d4000 -     0x7fff550e7fff  com.apple.CoreEmoji (1.0 - 69.15.8) <7D6B4C79-9A81-3BC2-A6F2-A0EAC9181A51> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff55549000 -     0x7fff555bbfff  com.apple.CoreNLP (1.0 - 130.15.19) <96E6DCEA-50A7-3644-B4C7-C09053237D55> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff5586b000 -     0x7fff55873fff  com.apple.CorePhoneNumbers (1.0 - 1) <B6129EE5-BCBE-3AF0-96DE-9BD2DB09FF0A> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff55a00000 -     0x7fff55a31ff3  com.apple.CoreServicesInternal (357 - 357) <A4FA9DB4-60E8-3841-BC80-A50980DBD0F4> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff55dbf000 -     0x7fff55e4dfff  com.apple.CoreSymbolication (10.0 - 64231) <1F3D9F1D-C68C-3DD3-8351-AD3DD0734EF3> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff55edc000 -     0x7fff56005fff  com.apple.coreui (2.1 - 498.31) <461130A9-F732-30F7-879E-12D841D27179> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff56006000 -     0x7fff5617fffb  com.apple.CoreUtils (5.7 - 570.51) <CA911463-80B6-31C3-8B0E-8E98DEC946DE> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff561d6000 -     0x7fff56239ffb  com.apple.framework.CoreWiFi (13.0 - 1370.6) <D70C1F0E-E477-3383-BD08-A1775549A038> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff5623a000 -     0x7fff5624aff3  com.apple.CrashReporterSupport (10.13 - 1) <DAAC3FB5-9346-3BBE-947F-669F27EC37DA> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff562cd000 -     0x7fff562dcffb  com.apple.framework.DFRFoundation (1.0 - 206) <35DDC870-7F5F-35DE-BCF3-730F74CCB35F> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff562dd000 -     0x7fff562e1ff7  com.apple.DSExternalDisplay (3.1 - 380) <7C796922-0BF0-336E-AC3F-7ED254655DBA> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff56364000 -     0x7fff563dbffb  com.apple.datadetectorscore (7.0 - 590.17) <40258B6B-E178-38F3-982E-656F1DC546C6> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff56429000 -     0x7fff5646afff  com.apple.DebugSymbols (185 - 185) <ABCC5477-D7AE-3E5C-8520-11EE6C6A96B8> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff5646b000 -     0x7fff565c3fff  com.apple.desktopservices (1.13 - ???) <AA0C236A-5AEF-3950-8326-52FC0A44DB91> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff574d7000 -     0x7fff57900ff7  com.apple.vision.FaceCore (3.3.3 - 3.3.3) <35CA568E-5C79-3BA7-8DC2-9D61F9681D2F> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff5b204000 -     0x7fff5b205fff  libmetal_timestamp.dylib (902.1.34) <7685E6F0-7822-37B5-B27E-EA0076561361> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3902/Libraries/libmetal_timestamp.dylib
    0x7fff5c8ab000 -     0x7fff5c8b0fff  com.apple.GPUWrangler (3.22.17 - 3.22.17) <A0FABCF5-A9A3-3A6C-BF09-A77C7FBB3153> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff5d70a000 -     0x7fff5d719fff  com.apple.GraphVisualizer (1.0 - 5) <DF5A214C-DF8F-37DA-8029-1BCF7AD74655> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff5d7fe000 -     0x7fff5d872ffb  com.apple.Heimdal (4.0 - 2.0) <694AD430-B772-3FF4-B093-4F0CA83A5100> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff5ec0f000 -     0x7fff5ec18fff  com.apple.IOAccelMemoryInfo (1.0 - 1) <C34C62C2-C885-3C12-AE2F-8050749954E9> /System/Library/PrivateFrameworks/IOAccelMemoryInfo.framework/Versions/A/IOAccelMemoryInfo
    0x7fff5ec19000 -     0x7fff5ec20ffb  com.apple.IOAccelerator (400.18 - 400.18) <3C72D7A2-85C0-313C-8EE7-330390BEDD9D> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff5ec24000 -     0x7fff5ec3dff7  com.apple.IOPresentment (1.0 - 37) <77E0EDB3-1875-3FD8-A4C6-5DECA4625694> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff5f04a000 -     0x7fff5f077ff7  com.apple.IconServices (367.1 - 369.0) <885C3446-28DA-393E-8877-37279D2DA88F> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff5f315000 -     0x7fff5f328fff  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <19ADBEAC-F5BB-370C-86E7-9E4DE98D76F0> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff5f343000 -     0x7fff5f43dff7  com.apple.LanguageModeling (1.0 - 159.15.14) <342FD8B4-A009-33D2-90AB-9094C40AD036> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff5f43e000 -     0x7fff5f486fff  com.apple.Lexicon-framework (1.0 - 33.15.9) <8226FD0F-7276-396D-B768-52D9B75E4A75> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff5f48d000 -     0x7fff5f493ff7  com.apple.LinguisticData (1.0 - 238.15.20) <3FF305AF-8D80-312C-8117-67768186D6DF> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff60290000 -     0x7fff602b8ff3  com.apple.spotlight.metadata.utilities (1.0 - 1191.31) <CA89497A-6B31-3A15-B0D4-0ED4950744A5> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff602b9000 -     0x7fff6034afff  com.apple.gpusw.MetalTools (1.0 - 1) <47C56CF3-47C1-3112-8D3A-006944472D3C> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff604ee000 -     0x7fff60507fff  com.apple.MobileKeyBag (2.0 - 1.0) <887D828A-F2BC-358A-A67C-C8C4B140E01F> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff60595000 -     0x7fff605bfff7  com.apple.MultitouchSupport.framework (2400.2 - 2400.2) <80FDB56C-F719-3A32-82D8-ACFF5B457E96> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff6082e000 -     0x7fff60838fff  com.apple.NetAuth (6.2 - 6.2) <F976AAB9-6523-38C7-B8C6-C8C4CE47B16A> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff62247000 -     0x7fff62256ffb  com.apple.PerformanceAnalysis (1.208 - 208) <250C6F27-7543-33C1-98BD-0F83633DB8AC> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff6423d000 -     0x7fff6425bfff  com.apple.ProtocolBuffer (1 - 263) <12A52CFA-40B9-3A0C-9811-310D12DF98C9> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff64523000 -     0x7fff64546fff  com.apple.RemoteViewServices (2.0 - 128) <1B6569C7-0EEC-35B1-8B74-1BA9E8BCD5EB> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff65e90000 -     0x7fff65fadfff  com.apple.Sharing (1153 - 1153) <14D24090-B4FD-3210-9E5D-BF5884252545> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff66d42000 -     0x7fff66fefff3  com.apple.SkyLight (1.600.0 - 336.61.1) <81670F7A-EA24-3F06-A8AB-0BB1D6941F67> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff677b8000 -     0x7fff677c5fff  com.apple.SpeechRecognitionCore (5.0.19 - 5.0.19) <F29C429F-AF5C-3618-873F-FD9E3FE0F2B7> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff685f7000 -     0x7fff68683fff  com.apple.Symbolication (10.0 - 64247) <505863A6-55E2-3729-A34B-787228D6C865> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff68b8c000 -     0x7fff68b98fff  com.apple.TCC (1.0 - 1) <6B9EB7AD-BFF6-3F65-AFBA-70D7A18466B0> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff68e01000 -     0x7fff68ec8ff7  com.apple.TextureIO (3.8.4 - 3.8.1) <6104FC0D-AB39-3B11-8CF4-14AD7F517AD6> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff68f87000 -     0x7fff6913fffb  com.apple.UIFoundation (1.0 - 550.23) <2FF3F20B-644B-3C98-93C7-7D1D9DD43254> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff69e17000 -     0x7fff69efdff7  com.apple.ViewBridge (388 - 388) <A21EF6E9-6F01-3951-9023-A07849436D9B> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff6a683000 -     0x7fff6a686ff7  com.apple.dt.XCTTargetBootstrap (1.0 - 1) <20E4C661-7BEA-3ECE-A9CA-673DF31169C3> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff6aab5000 -     0x7fff6aab7fff  com.apple.loginsupport (1.0 - 1) <13209147-3324-3E73-966F-CDC97691ACE4> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff6aab8000 -     0x7fff6aacdfff  com.apple.login (3.0 - 3.0) <4A99C39D-78A6-3D86-B13A-C88BF3F81479> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff6ad65000 -     0x7fff6ad9dff7  libCRFSuite.dylib (41.15.4) <E2612562-136E-3112-B5DF-966148A06DA0> /usr/lib/libCRFSuite.dylib
    0x7fff6ada0000 -     0x7fff6adabff7  libChineseTokenizer.dylib (28.15.3) <352F8ED1-ACC0-3518-8685-F5C8F574A3A9> /usr/lib/libChineseTokenizer.dylib
    0x7fff6ae3c000 -     0x7fff6ae3dfff  libDiagnosticMessagesClient.dylib (105) <BF8102DE-89C8-383B-8D68-0C86F70C06AE> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff6ae74000 -     0x7fff6b037ff3  libFosl_dynamic.dylib (18.3.2) <8683B04C-ADA8-32B9-8433-2823F1BBC964> /usr/lib/libFosl_dynamic.dylib
    0x7fff6b08c000 -     0x7fff6b0aaff7  libMobileGestalt.dylib (645.200.64) <2EECCE00-C7E7-386C-BB16-D9E5E3E52014> /usr/lib/libMobileGestalt.dylib
    0x7fff6b0ab000 -     0x7fff6b0abfff  libOpenScriptingUtil.dylib (176) <E113BA76-5FB7-35DF-9AF0-54987829E71E> /usr/lib/libOpenScriptingUtil.dylib
    0x7fff6b1eb000 -     0x7fff6b1ecffb  libSystem.B.dylib (1252.200.5) <128AFB16-2644-3045-B567-A6B886D2FB02> /usr/lib/libSystem.B.dylib
    0x7fff6b275000 -     0x7fff6b276ffb  libThaiTokenizer.dylib (2.15.1) <2E347CF6-3A69-3771-9818-9008072A0041> /usr/lib/libThaiTokenizer.dylib
    0x7fff6b289000 -     0x7fff6b29fffb  libapple_nghttp2.dylib (1.24.1) <2FB2162A-D457-3D82-8D31-4E4D90DD15CD> /usr/lib/libapple_nghttp2.dylib
    0x7fff6b2a0000 -     0x7fff6b2c9ffb  libarchive.2.dylib (54.200.3) <06C6B811-720F-30BD-BE8B-1F8FD8977FA6> /usr/lib/libarchive.2.dylib
    0x7fff6b2ca000 -     0x7fff6b349fef  libate.dylib (1.13.7) <41C7FC51-7BF8-3502-93CE-4F81E96AD122> /usr/lib/libate.dylib
    0x7fff6b34d000 -     0x7fff6b34dff7  libauto.dylib (187) <30CA32F2-A981-3CFB-8F33-284EDB596BA2> /usr/lib/libauto.dylib
    0x7fff6b422000 -     0x7fff6b432fff  libbsm.0.dylib (39.200.15) <1947D8F7-5C38-32C4-AE26-14DA171D739B> /usr/lib/libbsm.0.dylib
    0x7fff6b433000 -     0x7fff6b441ff7  libbz2.1.0.dylib (38.200.3) <02CF2E8B-DCE5-3EF8-946F-46F0052A39A3> /usr/lib/libbz2.1.0.dylib
    0x7fff6b442000 -     0x7fff6b499fff  libc++.1.dylib (400.9.4) <AC09FF88-1245-30DE-9BD0-F2578D04CA94> /usr/lib/libc++.1.dylib
    0x7fff6b49a000 -     0x7fff6b4b0ff7  libc++abi.dylib (400.16) <9FAABF5C-9B0A-3F9B-A057-B23D164F90A7> /usr/lib/libc++abi.dylib
    0x7fff6b4b1000 -     0x7fff6b4b1ff3  libcharset.1.dylib (51.200.5) <1FDBB9DF-A530-3E42-833D-4305AD986BF3> /usr/lib/libcharset.1.dylib
    0x7fff6b4b2000 -     0x7fff6b4c2ffb  libcmph.dylib (6.15.1) <1A07BE15-899B-3F27-A672-74F45AC4FAAB> /usr/lib/libcmph.dylib
    0x7fff6b4c3000 -     0x7fff6b4dbfe7  libcompression.dylib (52.200.12) <4BF1AAF1-93E6-3541-B56F-D597E5345C9C> /usr/lib/libcompression.dylib
    0x7fff6b784000 -     0x7fff6b79afff  libcoretls.dylib (155.200.6) <464B3613-8676-3A46-B551-447E7039795C> /usr/lib/libcoretls.dylib
    0x7fff6b79b000 -     0x7fff6b79cff3  libcoretls_cfhelpers.dylib (155.200.6) <FA0232EF-DFC7-3BDC-9290-4CE442AF55A8> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff6be13000 -     0x7fff6be69ffb  libcups.2.dylib (462.7) <23099FCC-06A1-34F0-906E-4E66FA77A440> /usr/lib/libcups.2.dylib
    0x7fff6bfa0000 -     0x7fff6bfa0fff  libenergytrace.dylib (17.200.1) <FF926037-F562-32DC-B685-2713C3BEE209> /usr/lib/libenergytrace.dylib
    0x7fff6bfc8000 -     0x7fff6bfc9fff  libffi.dylib (18.1) <BB9679FA-DACD-38B5-B866-312AE968856E> /usr/lib/libffi.dylib
    0x7fff6bfd2000 -     0x7fff6bfd7fff  libgermantok.dylib (17.15.2) <5F91FF2D-85DC-366C-8EC0-73B36C90F776> /usr/lib/libgermantok.dylib
    0x7fff6bfd8000 -     0x7fff6bfddff7  libheimdal-asn1.dylib (520.200.9) <475D5EA2-344E-3517-A900-26354571560C> /usr/lib/libheimdal-asn1.dylib
    0x7fff6c009000 -     0x7fff6c0faff7  libiconv.2.dylib (51.200.5) <AAA26A4D-12C0-3CF5-AE76-9AA1912FAE7B> /usr/lib/libiconv.2.dylib
    0x7fff6c0fb000 -     0x7fff6c35eff7  libicucore.A.dylib (62100.0.1) <3CC5ACB5-5BF3-3952-B646-1F8F2E3B1C9C> /usr/lib/libicucore.A.dylib
    0x7fff6c3ab000 -     0x7fff6c3acfff  liblangid.dylib (128.15.1) <914A6C07-0915-3CB2-A50B-B4C2755209ED> /usr/lib/liblangid.dylib
    0x7fff6c3ad000 -     0x7fff6c3c5fff  liblzma.5.dylib (10.200.3) <F229DD7B-6D52-3EBA-87AF-3A106198BD22> /usr/lib/liblzma.5.dylib
    0x7fff6c3dd000 -     0x7fff6c48dff7  libmecab.1.0.0.dylib (779.15.20) <883F0FCF-E73E-31E5-8397-838BF080D0C8> /usr/lib/libmecab.1.0.0.dylib
    0x7fff6c48e000 -     0x7fff6c6cafff  libmecabra.dylib (779.15.20) <52D4D684-0951-341F-BEA3-C566E7F55C30> /usr/lib/libmecabra.dylib
    0x7fff6c8a2000 -     0x7fff6cbf7fff  libnetwork.dylib (1229.200.90) <C47238A7-CE0D-3F28-A418-3764376A8651> /usr/lib/libnetwork.dylib
    0x7fff6cc81000 -     0x7fff6cc84047  libobjc-trampolines.dylib (747) <BDCC928A-12D2-36A4-9D61-694474B0D2CB> /usr/lib/libobjc-trampolines.dylib
    0x7fff6cc85000 -     0x7fff6d336fef  libobjc.A.dylib (747) <733C6D28-698E-3EA7-965B-A696796602C0> /usr/lib/libobjc.A.dylib
    0x7fff6d349000 -     0x7fff6d34dffb  libpam.2.dylib (22.200.1) <2AEA51AA-4350-33E5-B8FA-2350F30B5D6C> /usr/lib/libpam.2.dylib
    0x7fff6d350000 -     0x7fff6d386ff7  libpcap.A.dylib (79.200.4) <0D40809A-B3FF-352D-8818-5D35FA830DBD> /usr/lib/libpcap.A.dylib
    0x7fff6d4a0000 -     0x7fff6d4b8ff3  libresolv.9.dylib (65.200.2) <AD8973EE-6CF5-3329-9826-9DABBFFDC346> /usr/lib/libresolv.9.dylib
    0x7fff6d50c000 -     0x7fff6d6d9feb  libsqlite3.dylib (274.15) <93C742A9-FB33-3D0F-8228-C7F3A3D89575> /usr/lib/libsqlite3.dylib
    0x7fff6d967000 -     0x7fff6d96affb  libutil.dylib (51.200.4) <7F86AADB-8393-3612-BFC0-62821A499A06> /usr/lib/libutil.dylib
    0x7fff6d96b000 -     0x7fff6d978fff  libxar.1.dylib (404) <5CED538B-C843-3C46-966A-4451E2D75B95> /usr/lib/libxar.1.dylib
    0x7fff6d97d000 -     0x7fff6da60ffb  libxml2.2.dylib (32.6) <DCF7156E-07C2-3254-8E85-149F66193E61> /usr/lib/libxml2.2.dylib
    0x7fff6da61000 -     0x7fff6da89ff3  libxslt.1.dylib (16.1) <AB321C28-5A8E-30DE-B6A1-7EA22557986F> /usr/lib/libxslt.1.dylib
    0x7fff6da8a000 -     0x7fff6da9cff3  libz.1.dylib (70.200.4) <A12B1668-05FE-3CED-BE73-C5BDC0F4CF7D> /usr/lib/libz.1.dylib
    0x7fff6db0d000 -     0x7fff6db11fff  libcache.dylib (81) <D6AD67F5-DB38-3E38-8DBA-A67EA0F3ECA3> /usr/lib/system/libcache.dylib
    0x7fff6db12000 -     0x7fff6db1cfff  libcommonCrypto.dylib (60118.200.5) <0BF2FA5C-03FE-3121-A109-F30EA1F06F68> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6db1d000 -     0x7fff6db24fff  libcompiler_rt.dylib (63.4) <CC2BE749-AFE1-39AF-AB04-6F11915111F0> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6db25000 -     0x7fff6db2effb  libcopyfile.dylib (146.200.2) <BD44F72A-2B92-3627-BCC4-A7470E2AE01E> /usr/lib/system/libcopyfile.dylib
    0x7fff6db2f000 -     0x7fff6dbb3fd7  libcorecrypto.dylib (602.200.43) <0C5D22EF-C61F-3B1F-AB6D-D63142F08E40> /usr/lib/system/libcorecrypto.dylib
    0x7fff6dc39000 -     0x7fff6dc74ff7  libdispatch.dylib (1008.200.71) <A4B06221-BF54-37CF-B78A-20DA3BC5254E> /usr/lib/system/libdispatch.dylib
    0x7fff6dc75000 -     0x7fff6dca2ff7  libdyld.dylib (623.1) <38C87B5B-D1EE-3FDE-A36D-40AFCABE11BF> /usr/lib/system/libdyld.dylib
    0x7fff6dca3000 -     0x7fff6dca3ffb  libkeymgr.dylib (30) <0533EA96-9962-3FCB-874A-FB4F1AA7C3E3> /usr/lib/system/libkeymgr.dylib
    0x7fff6dca4000 -     0x7fff6dcb0ff7  libkxld.dylib (4903.200.274.31.2) <7D22C3B8-9636-339C-956A-50E8E8B1EABC> /usr/lib/system/libkxld.dylib
    0x7fff6dcb1000 -     0x7fff6dcb1ff7  liblaunch.dylib (1336.200.79) <AFC9E2A1-2C8C-30BC-9459-3372C9804C9E> /usr/lib/system/liblaunch.dylib
    0x7fff6dcb2000 -     0x7fff6dcb7fff  libmacho.dylib (917) <7C6B1E1B-E405-3458-BB35-73454C21C496> /usr/lib/system/libmacho.dylib
    0x7fff6dcb8000 -     0x7fff6dcbaff7  libquarantine.dylib (86.200.9) <19E80E42-E9F9-3CD3-8355-4026D6F3795E> /usr/lib/system/libquarantine.dylib
    0x7fff6dcbb000 -     0x7fff6dcbcff3  libremovefile.dylib (45.200.2) <591A2679-20B7-3570-9314-A65DB41E4C7A> /usr/lib/system/libremovefile.dylib
    0x7fff6dcbd000 -     0x7fff6dcd4ff7  libsystem_asl.dylib (356.200.3) <822D70E3-86A6-3A17-9473-DA1966BBF301> /usr/lib/system/libsystem_asl.dylib
    0x7fff6dcd5000 -     0x7fff6dcd5fff  libsystem_blocks.dylib (73) <43A0E8B0-B704-3392-9B0B-D39F830E4E32> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6dcd6000 -     0x7fff6dd5eff7  libsystem_c.dylib (1272.200.23) <F3D15ED4-0AA4-35E2-AE85-CFA2408CA25E> /usr/lib/system/libsystem_c.dylib
    0x7fff6dd5f000 -     0x7fff6dd62ffb  libsystem_configuration.dylib (963.200.20) <A1AA99E7-DC85-33AA-8245-3B4787DAC7D9> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6dd63000 -     0x7fff6dd66ff3  libsystem_coreservices.dylib (63) <E868745A-5F30-328A-9FEC-B2A146AB6DB9> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6dd67000 -     0x7fff6dd6dfff  libsystem_darwin.dylib (1272.200.23) <14AE99F2-83AB-3DA4-924E-1E8C8FD6DF27> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6dd6e000 -     0x7fff6dd74ff3  libsystem_dnssd.dylib (878.200.29) <388BB32E-A7B6-3A70-BAFC-82BF93863821> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff6dd75000 -     0x7fff6ddc1ffb  libsystem_info.dylib (517.200.9) <F195E3C7-C085-31E4-8D04-541251541C8A> /usr/lib/system/libsystem_info.dylib
    0x7fff6ddc2000 -     0x7fff6dde9fff  libsystem_kernel.dylib (4903.200.274.31.2) <03CBB8A3-02C6-3B2A-84F3-0E3D849DE337> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6ddea000 -     0x7fff6de35ffb  libsystem_m.dylib (3158.200.7) <9F07CC1E-2343-3250-ACFF-B02D7F8283CC> /usr/lib/system/libsystem_m.dylib
    0x7fff6de36000 -     0x7fff6de5aff7  libsystem_malloc.dylib (166.200.50) <664753F4-A19C-3CAD-8C1E-9E719DC63ED0> /usr/lib/system/libsystem_malloc.dylib
    0x7fff6de5b000 -     0x7fff6de66ff3  libsystem_networkextension.dylib (767.200.37) <BB5D70D5-5AEC-33CC-89C6-FB61263B25FB> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6de67000 -     0x7fff6de6dff7  libsystem_notify.dylib (172.200.15) <33F0EA68-9CDF-343E-AB34-99E8AB529396> /usr/lib/system/libsystem_notify.dylib
    0x7fff6de6e000 -     0x7fff6de77ff7  libsystem_platform.dylib (177.200.11) <7C3B2FCA-8FCC-3A10-A965-2ECF84B10DE0> /usr/lib/system/libsystem_platform.dylib
    0x7fff6de78000 -     0x7fff6de82ff7  libsystem_pthread.dylib (330.200.39) <D4EFDB4D-9019-3375-A14A-C78BE6247880> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6de83000 -     0x7fff6de86ffb  libsystem_sandbox.dylib (851.200.118) <1783F33B-5C81-39A0-9A5C-1EA27C4E0407> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6de87000 -     0x7fff6de89ff3  libsystem_secinit.dylib (30.200.8) <10D0E9E1-2297-3A6C-9364-B108D266F684> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6de8a000 -     0x7fff6de91ff7  libsystem_symptoms.dylib (820.207.83) <C92CAA08-70AE-3241-9783-A69546FD3C01> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6de92000 -     0x7fff6dea7ff7  libsystem_trace.dylib (906.200.66) <6C0939FA-95A0-3BC1-B35E-A983964DB16B> /usr/lib/system/libsystem_trace.dylib
    0x7fff6dea9000 -     0x7fff6deaeffb  libunwind.dylib (35.4) <75719F06-238A-3097-8254-62520AC44139> /usr/lib/system/libunwind.dylib
    0x7fff6deaf000 -     0x7fff6dedfff7  libxpc.dylib (1336.200.79) <7A892115-54D4-3C57-9BD9-9CB57900AF7A> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 150757
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=405.4M resident=0K(0%) swapped_out_or_unallocated=405.4M(100%)
Writable regions: Total=694.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=694.9M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        2 
Activity Tracing                   256K        2 
CG backing stores                 19.9M        5 
CG image                            72K        6 
CoreAnimation                       72K        7 
CoreGraphics                         8K        2 
CoreImage                           24K        3 
CoreUI image data                  472K        5 
CoreUI image file                  500K        6 
Foundation                          36K        4 
Kernel Alloc Once                    8K        2 
MALLOC                           275.3M       47 
MALLOC guard page                   32K        8 
MALLOC_LARGE (reserved)            456K        3         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        2         reserved VM address space (unallocated)
Memory Tag 242                      12K        2 
STACK GUARD                       56.0M       13 
Stack                             13.6M       13 
VM_ALLOCATE                         88K       10 
__DATA                            25.2M      243 
__FONT_DATA                          4K        2 
__LINKEDIT                       220.3M        7 
__TEXT                           185.2M      246 
__UNICODE                          560K        2 
mapped file                       58.4M       27 
shared memory                     3160K       16 
===========                     =======  ======= 
TOTAL                              1.2G      659 
TOTAL, minus reserved VM space   859.2M      659 

```

</details>

### PR DESCRIPTION
**Pull request by davidebeatrici**
Fixes #3471.

Since macOS Mojave, passing `NULL` to `CGEventTapEnable()` causes a segmentation fault.

This pull request also:

- Initializes pointers to `NULL` in the constructor.
- Adds a check in the destructor so that `NULL` is not passed to `CFRunLoopStop()`.
- Adds a check to `enabled()`, so that `NULL` is not passed to `CGEventTapIsEnabled()`.

### CODE REVIEW

File: src/mumble/GlobalShortcut_macx.mm [hunk 1]
```diff
@@ -147,8 +152,9 @@
 	                        GlobalShortcutMac::callback,
 	                        this);
 
-	if (! port) {
+	if (!port) {
 		qWarning("GlobalShortcutMac: Unable to create EventTap. Global Shortcuts will not be available.");
+		g.mw->msgBox(QLatin1String(osPrivacySettingsError));
```
Comment (hacst) [inline src/mumble/GlobalShortcut_macx.mm]: Does this work? I'm kinda doubtful ```g.mw``` exists at that point. From a quick check it looks like global shortcuts are created in the main window construction phase and before construction concludes g.mw is not set.

If that is the case maybe check ```QMessageBox``` for ways to display a modal without needing a parent. This would also allow you to get rid of the heavy includes.

Comment (davidebeatrici) [reply src/mumble/GlobalShortcut_macx.mm]: `g.mw->msgBox()` doesn't actually show a message box, it prints the message in the chat box.

Comment (hacst) [reply src/mumble/GlobalShortcut_macx.mm]: I see. Maybe we should rename it ;) Doesn't resolve the issue though.

Comment (davidebeatrici) [reply src/mumble/GlobalShortcut_macx.mm]: I agree, I initially though `msgBox()` was related to QMessageBox too.

File: src/mumble/GlobalShortcut_macx.h [hunk 2]
```diff
@@ -12,7 +12,9 @@
 #include <ApplicationServices/ApplicationServices.h>
 
 #include "GlobalShortcut.h"
-#include "Global.h"
+
+// We can't mark it as translation in GlobalShortcut_macx.mm because it's not processed by 'lupdate'.
+static const char *osPrivacySettingsError = QT_TRANSLATE_NOOP("GlobalShortcutMac", "Unable to initialize the global shortcuts handler. Please check that your operating system's privacy settings allow Mumble to use the accessibility functions.");
```
[the remark this answers is not in the document]
Comment (davidebeatrici) [reply src/mumble/GlobalShortcut_macx.h]: Unfortunately it doesn't work, `lupdate` doesn't parse Objective-C++: https://bugreports.qt.io/browse/QTBUG-44808

[the remark this answers is not in the document]
Comment (davidebeatrici) [reply src/mumble/GlobalShortcut_macx.h]: I propose to create a function in `GlobalShortcut` which shows the translated message.

What do you think about that?

File: src/mumble/GlobalShortcut_macx.mm (hunk 1 above)
Comment (davidebeatrici) [reply src/mumble/GlobalShortcut_macx.mm]: I tested the pull request.

Calling `g.mw->msgBox()` doesn't cause a crash, however the message is not shown because the chat box is not created yet:
```
QCoreApplication::postEvent: Unexpected null receiver
```

**Comment by davidebeatrici** [comment]
As fixing the crash is mandatory for 1.3, I'm going to remove the log part, we'll look into it in future.
