### PR TITLE
FIX(client): Fixes link context menu creation for channels

### LINKED ISSUE #2961: Add a context menu for channels "links" in log view.
Currently there is a context menu for users only, but not yet for channels.

A context menu would help for example to follow another user who joined another channel.

Also left click on a user focuses him, this sould be the same for channel links.

### PR DESCRIPTION
**Pull request by Hartmnt**
The commit 902fe5841ca03f59b introduced links in the log for users and channels. This either never worked correctly, or regressed due to an undocumented behavior change in Qt. The 'channelid' stored in the host part of a QUrl is automatically converted to an IP address (e.g. '1' -> '0.0.0.1') which lets the channel lookup fail. A different code path for clients was present, so the issue was not observed often (or at all) there.

This commit changes the host part composition to contain a string (e.g. '1' > 'id.1') and makes sure this new string is parsed correctly.

Fixes #2961

### CODE REVIEW

File: src/mumble/MainWindow.cpp [hunk 1]
```diff
@@ -840,7 +840,8 @@ bool MainWindow::handleSpecialContextMenu(const QUrl &url, const QPoint &pos_, b
 			}
 		} else {
 			QByteArray qbaServerDigest = QByteArray::fromBase64(url.path().remove(0, 1).toLatin1());
-			cuContextUser              = ClientUser::get(url.host().toInt(&ok, 10));
+			QString id                 = url.host().split(".").value(1, "-1");
```
Comment (Krzmbrzl) [inline src/mumble/MainWindow.cpp:843]: Maybe we should add a small comment here, explaining what format we expect the url's host to be in.

File: src/mumble/MainWindow.cpp [hunk 2]
```diff
@@ -857,7 +858,8 @@ bool MainWindow::handleSpecialContextMenu(const QUrl &url, const QPoint &pos_, b
 	} else if (url.scheme() == QString::fromLatin1("channelid")) {
 		bool ok;
 		QByteArray qbaServerDigest = QByteArray::fromBase64(url.path().remove(0, 1).toLatin1());
-		cContextChannel            = Channel::get(url.host().toInt(&ok, 10));
+		QString id                 = url.host().split(".").value(1, "-1");
```
Comment (Krzmbrzl) [inline src/mumble/MainWindow.cpp:861]: The same comment should then probably be added here as well

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thanks for fixing this :+1:
