### PR TITLE
FIX(client): Send empty buffer in PA write_callback instead of nothing

### LINKED ISSUE #4883: no audio output after applying settings
After applying the settings I get no more audio output. Others still hear me.

I don't even get a "speaking" symbol on the others. Except someone is speaking while I'm applying the settings, which results in the speaking symbol getting stuck (but I can't hear that person speaking anymore).

**Steps to Reproduce**
1. Connect to a server.
2. Open the settings.
3. Click "Apply" or "OK" (don't actually change a setting)

&nbsp;

What didn't help:
- disabling echo cancellation
- disabling positional audio
- restarting pulseaudio (`pulseaudio -k`)

&nbsp;

**Desktop (please complete the following information):**
 - OS: Debian 11/Bullseye (Testing / Beta)
 - Version: Mumble and Murmur 1.3.4-1 (by Debian package manager)
   - Also tested Mumble from [FlatHub](https://www.flathub.org/apps/details/info.mumble.Mumble) (same problem)

&nbsp;

Maybe related:
- #3278 _Output cuts out on my end/Input still works_
- #3345 _Mumble freezes audio after settings change under FreeBSD_
- #4679 _Audio isn't working when opening Mumble_

&nbsp;

<details>
<summary>screenshots and logs</summary>

grafik

grafik

```
$ LANG=C.UTF-8 mumble
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<W>2021-03-24 21:47:48.373 JackAudioSystem: unable to open client due to 2 errors:
<W>2021-03-24 21:47:48.373 JackAudioSystem: JackFailure - overall operation failed
<W>2021-03-24 21:47:48.373 JackAudioSystem: JackServerFailed - unable to connect to the JACK server
<D>2021-03-24 21:47:49.476 libopus 1.3.1 from libopus.so.0
<W>2021-03-24 21:47:49.477 CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
<W>2021-03-24 21:47:49.479 Theme: "Classic"
<W>2021-03-24 21:47:49.479 Style: "Old Style"
<W>2021-03-24 21:47:49.479 --> qss: ":themes/Classic/Classic.qss"
<W>2021-03-24 21:47:49.481 Locale is "C" (System: "C")
<W>2021-03-24 21:47:49.636 Database SQLite: "3.34.1"
<W>2021-03-24 21:47:49.658 Updating application palette
<W>2021-03-24 21:47:49.719 GlobalShortcutX: Using XI2 2.3
<W>2021-03-24 21:47:50.182 AudioInput: Opus encoder set for VOIP
<W>2021-03-24 21:47:50.182 AudioInput: 45000 bits/s, 48000 hz, 480 sample
<W>2021-03-24 21:47:50.183 PulseAudio: Starting input alsa_input.pci-0000_00_14.2.analog-stereo
<W>2021-03-24 21:47:50.183 PulseAudio: Starting echo: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
<W>2021-03-24 21:47:50.184 PulseAudio: Starting output: alsa_output.pci-0000_00_14.2.analog-stereo
<W>2021-03-24 21:47:50.184 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-24 21:47:50.184 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2021-03-24 21:47:50.203 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 1 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-24 21:47:50.204 AudioInput: ECHO CANCELLER ACTIVE
<W>2021-03-24 21:47:51.943 Database SQLite: "3.34.1"
<W>2021-03-24 21:47:51.943 OpenSSL Support: 1 (OpenSSL 1.1.1j  16 Feb 2021)
<W>2021-03-24 21:47:51.982 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2021-03-24 21:48:02.810 AudioInput: Opus encoder set for VOIP
<W>2021-03-24 21:48:02.810 AudioInput: 45000 bits/s, 48000 hz, 480 sample
<W>2021-03-24 21:48:02.813 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2021-03-24 21:48:02.816 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 1 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-24 21:48:02.819 AudioInput: ECHO CANCELLER ACTIVE
<W>2021-03-24 21:48:11.092 PulseAudio: Forcibly disconnected from PulseAudio
```
</details>

### PR DESCRIPTION
**Pull request by Hartmnt**
When applying the settings, Mumble will restart the AudioSystems for input and output. During this time, if a PulseAudio write_callback happens, Mumble will write nothing and just return. However, this behavior will cause PulseAudio to never request a callback again, disabling audio output for the user until mumble is restarted. ( See: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1132 )

This commit instead changes the code to return an empty buffer in that case instead, such that PulseAudio will continue to send Mumble write_callbacks and keep audio output intact.

Special thanks to GitHub User @WGH- who found out about this fix and originally posted the patch in the Mumble issue tracker.

Fixes #4883

Co-Authored-By: WGH <wgh@torlan.ru>

### CODE REVIEW

**Review by davidebeatrici — APPROVED** [review]

File: src/mumble/PulseAudio.cpp [hunk 1]
```diff
@@ -566,15 +566,23 @@ void PulseAudioSystem::write_callback(pa_stream *s, size_t bytes, void *userdata
 	PulseAudioSystem *pas = reinterpret_cast< PulseAudioSystem * >(userdata);
 	Q_ASSERT(s == pas->pasOutput);
 
+	const auto &pa = pas->m_pulseAudio;
```
Comment (Krzmbrzl) [inline src/mumble/PulseAudio.cpp:569]: Use of `auto` violates our coding guidelines - see https://github.com/mumble-voip/mumble/blob/master/CODING_GUIDELINES.md#use-of-auto

```suggestion
	const PulseAudio &pa = pas->m_pulseAudio;
```

File: src/mumble/PulseAudio.cpp [hunk 2]
```diff
@@ -566,15 +566,23 @@ void PulseAudioSystem::write_callback(pa_stream *s, size_t bytes, void *userdata
...
 	PulseAudioOutput *pao = dynamic_cast< PulseAudioOutput * >(ao.get());
 
 	if (!pao) {
+		// The AudioSystem pointer is invalid, probably because of a AudioSystem restart.
+		// However, PA expects this callback to return exactly the provided number of
+		// bytes. Failing to do so will cause PA to never call this again,
+		// effectively removing the audio output completely until Mumble is restarted.
+		// See: https://github.com/mumble-voip/mumble/issues/4883
+		// See: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1132
+		unsigned char buffer[bytes] = {};
```
Comment (Krzmbrzl) [inline src/mumble/PulseAudio.cpp:581]: This is not standard C++, but a compiler extension (variable-size arrays). This will have to be changed in #5960

(Just take this as a note though - I see the rest of the file uses this anyway, so let's not bother at this point yet)

File: src/mumble/PulseAudio.cpp [hunk 3]
```diff
@@ -566,15 +566,23 @@ void PulseAudioSystem::write_callback(pa_stream *s, size_t bytes, void *userdata
 	PulseAudioSystem *pas = reinterpret_cast< PulseAudioSystem * >(userdata);
 	Q_ASSERT(s == pas->pasOutput);
 
+	const auto &pa = pas->m_pulseAudio;
+
 	AudioOutputPtr ao     = Global::get().ao;
 	PulseAudioOutput *pao = dynamic_cast< PulseAudioOutput * >(ao.get());
 
 	if (!pao) {
+		// The AudioSystem pointer is invalid, probably because of a AudioSystem restart.
```
Comment (Krzmbrzl) [inline src/mumble/PulseAudio.cpp:575]:
```suggestion
		// The AudioSystem pointer is invalid, probably because of an AudioSystem restart.
```

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.5.x|[](https://github.com/mumble-voip/mumble/pull/6053)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/mumble-voip/mumble/actions/runs/4078484353) for details
