### PR TITLE
FIX(protocol): Handle protobuf serialization return values

### LINKED ISSUE #7102: Latest Protobuf release now uses nodiscard, which causes compiler warnings
### Description

comet:/usr/src/mumble/build# make
[  1%] Built target overlay_gl
[  1%] Built target overlay_gl_x86
[  2%] Built target wow_x64
[  3%] Built target link
[  4%] Built target amongus
[  4%] Built target aoc
[  5%] Built target arma2
[  5%] Built target bf1
[  5%] Built target bf1942
[  6%] Built target bf2
[  6%] Built target bf2142
[  7%] Built target bf3
[  7%] Built target bf4
[  7%] Built target bf4_x86
[  8%] Built target bfbc2
[  8%] Built target bfheroes
[  8%] Built target blacklight
[  9%] Built target borderlands
[  9%] Built target borderlands2
[  9%] Built target breach
[ 10%] Built target cod2
[ 11%] Built target cod4
[ 11%] Built target cod5
[ 11%] Built target codmw2
[ 12%] Built target codmw2so
[ 12%] Built target cs
[ 12%] Built target dys
[ 13%] Built target etqw
[ 13%] Built target ffxiv
[ 14%] Built target ffxiv_x64
[ 14%] Built target gmod
[ 15%] Built target grounded
[ 16%] Built target gtaiv
[ 16%] Built target gtasa
[ 17%] Built target gtav
[ 18%] Built target gw
[ 18%] Built target insurgency
[ 18%] Built target jc2
[ 19%] Built target lol
[ 19%] Built target lotro
[ 19%] Built target ql
[ 20%] Built target rl
[ 21%] Built target se
[ 21%] Built target sr
[ 22%] Built target ut2004
[ 22%] Built target ut3
[ 22%] Built target ut99
[ 23%] Built target wolfet
[ 23%] Built target wow
[ 23%] Built target plugins
[ 23%] Built target link_tester
[ 24%] Built target spdlog
[ 24%] Built target generate_license_header
[ 24%] Built target TracyClient
[ 25%] Built target shared_autogen_timestamp_deps
[ 25%] Built target shared_autogen
[ 25%] Building CXX object src/CMakeFiles/shared.dir/MumbleProtocol.cpp.o
/usr/src/mumble/src/MumbleProtocol.cpp: In function ‘std::size_t Mumble::Protocol::encodeProtobuf(const google::protobuf::Message&, std::vector<unsigned char>&, std::size_t, std::size_t, bool)’:
/usr/src/mumble/src/MumbleProtocol.cpp:105:48: error: ignoring return value of ‘bool google::protobuf::MessageLite::SerializePartialToArray(void*, int) const’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  105 |                 message.SerializePartialToArray(buffer.data() + offset, static_cast< int >(serializedSize));
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/google/protobuf/generated_message_tctable_decl.h:24,
                 from /usr/src/mumble/build/src/MumbleUDP.pb.h:24,
                 from /usr/src/mumble/src/MumbleProtocol.h:9,
                 from /usr/src/mumble/src/MumbleProtocol.cpp:6:
/usr/include/google/protobuf/message_lite.h:770:44: note: declared here
  770 |   PROTOBUF_FUTURE_ADD_EARLY_NODISCARD bool SerializePartialToArray(
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/shared.dir/build.make:247: src/CMakeFiles/shared.dir/MumbleProtocol.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3626: src/CMakeFiles/shared.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

### Steps to reproduce

cmake .. -DPostgreSQL_INCLUDE_DIR=/usr/local/pgsql/include -DPostgreSQL_LIBRARY=/usr/local/pgsql/lib/libpq.so 
make -j 16

### Mumble version

v1.6.870

### Mumble component

Both

### OS

Linux

### Reproducible?

Yes

### Additional information

/usr/src/mumble/src/MumbleProtocol.cpp:105:48: error: ignoring return value of ‘bool google::protobuf::MessageLite::SerializePartialToArray(void*, int) const’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  105 |                 message.SerializePartialToArray(buffer.data() + offset, static_cast< int >(serializedSize));

/usr/include/google/protobuf/message_lite.h:770:44: note: declared here
  770 |   PROTOBUF_FUTURE_ADD_EARLY_NODISCARD bool SerializePartialToArray(

### Relevant log output

```shell

```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by maxer137**
Fix compilation error caused by ignoring the return value of protobuf serialization functions marked with [[nodiscard]].

The errors observed were:
```
/mumble/src/MumbleProtocol.cpp:105:3: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  105 |                 message.SerializePartialToArray(buffer.data() + offset, static_cast< int >(serializedSize));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mumble/src/Connection.cpp:176:2: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  176 |         msg.SerializeToArray(uc + 6, static_cast< int >(len));
      |         ^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Both SerializeToArray and SerializePartialToArray now store and check their return values. In case of failure, a warning is logged, and the function exits early to avoid using invalid data.

Closes #7102

### CODE REVIEW

**Comment by Hartmnt** [comment]
This would fix #7102, correct? Would you mind adding the issue as to be closed by this PR? Also your commit authorship information is broken, not sure if this is intentional.

**Comment by maxer137** [comment]
> This would fix #7102, correct? Would you mind adding the issue as to be closed by this PR? 

Added 👍 

> Also your commit authorship information is broken, not sure if this is intentional.

Not sure what changed in my configuration, but it wasn't intentional. Fixed now :)

File: src/Connection.cpp [hunk 1]
```diff
@@ -173,7 +173,12 @@ void Connection::messageToNetwork(const ::google::protobuf::Message &msg, Mumble
 	qToBigEndian< quint16 >(static_cast< quint16 >(msgType), &uc[0]);
 	qToBigEndian< quint32 >(static_cast< unsigned int >(len), &uc[2]);
 
-	msg.SerializeToArray(uc + 6, static_cast< int >(len));
+	bool success = msg.SerializeToArray(uc + 6, static_cast< int >(len));
+	if (!success) {
+		qWarning("Failed to serialize protobuf message");
+		cache.clear();
+		return;
+	}
```
Comment (Krzmbrzl) [inline src/Connection.cpp:181]: I don't think call-sites are prepared to handle this function producing an empty buffer. We should probably make the function return a `bool` to indicate the success/failure state (and make it `[[nodiscard]]`) in order to let call-sites react to it.

(I do realize that there were other circumstances under which this function could yield an unchanged buffer but I'm not sure that this code path was ever executed…)

File: src/MumbleProtocol.cpp [hunk 2]
```diff
@@ -102,7 +102,12 @@ namespace Protocol {
 
 		buffer.resize(serializedSize + offset);
 
-		message.SerializePartialToArray(buffer.data() + offset, static_cast< int >(serializedSize));
+		bool success = message.SerializePartialToArray(buffer.data() + offset, static_cast< int >(serializedSize));
+
+		if (!success) {
+			qWarning("Failed to serialize protobuf message");
+			return 0;
```
Comment (Krzmbrzl) [inline src/MumbleProtocol.cpp]: Looking at how this function is used, I don't think simply returning zero will prevent us from entering an inconsistent state.

Again, I do realize that this is what this function does in other code-paths as well 👀

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
Is there a way we can actually cause the serialization to fail in a test case? I'm somewhat unsure with regards to the error handling (or lack thereof) if these functions fail. It seems like they could easily throw us into some undefined state that will cause trouble later on…

File: src/Connection.cpp [hunk 3]
```diff
@@ -158,28 +158,36 @@ void Connection::socketDisconnected() {
...
+	return true;
 }
 
 void Connection::sendMessage(const ::google::protobuf::Message &msg, Mumble::Protocol::TCPMessageType msgType,
 							 QByteArray &cache) {
 	if (cache.isEmpty()) {
-		messageToNetwork(msg, msgType, cache);
+		if (!messageToNetwork(msg, msgType, cache)) {
+			qWarning("Sending message to network failed");
```
Comment (Krzmbrzl) [inline src/Connection.cpp:189]:
```suggestion
			qWarning("Sending message to network failed");
			return;
```

File: src/MumbleProtocol.cpp [hunk 4]
```diff
@@ -97,12 +99,19 @@ namespace Protocol {
...
+			return std::nullopt;
 		}
+		std::vector< byte > temp(serializedSize);
+		bool success = message.SerializePartialToArray(temp.data(), static_cast< int >(serializedSize));
+		if (!success) {
+			qWarning("Failed to serialize protobuf message");
+			return std::nullopt;
+		}
+		if (buffer.size() < offset + serializedSize)
+			buffer.resize(offset + serializedSize);
```
Comment (Krzmbrzl) [inline src/MumbleProtocol.cpp]: Iirc making `buffer` exactly as long as required (not longer) was intentional. Do you have a reason for changing that behavior?

File: src/MumbleProtocol.cpp [hunk 5]
```diff
@@ -415,12 +448,15 @@ namespace Protocol {
 			// Store the pre-encoded packet
 			// The max-size is the size of the used field (float) plus 1 byte overhead for encoding the field type and
 			// number
-			bool successful = encodeProtobuf(
+			auto maybeSize = encodeProtobuf(
```
Comment (Krzmbrzl) [inline src/MumbleProtocol.cpp]:
```suggestion
			std::optional<std::size_t> maybeSize = encodeProtobuf(
```
Please use explicit types instead of `auto`. See also https://github.com/mumble-voip/mumble/blob/master/CODING_GUIDELINES.md#use-of-auto

File: src/MumbleProtocol.cpp (hunk 4 above)
Comment (maxer137) [reply src/MumbleProtocol.cpp]: I misread the code; I thought it could only grow, not shrink. That's my bad.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thanks for fixing this :+1:

**Comment by Krzmbrzl** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.6.x|[](https://github.com/mumble-voip/mumble/pull/7161)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/mumble-voip/mumble/actions/runs/24346223038) for details
