### PR TITLE
FIX(server): Restore CLI flag --help output for mumble-server

### LINKED ISSUE #6934: mumble-server is missing cli command output
### Description

Since #6243 (I assume) mumble-server will no longer respond to cli commands such as ``./mumble-server --help``

It just quits without printing anything.

However, if no cli arguments are specified, it starts up normally.

Notably the client behaves correctly.

### Steps to reproduce

``./mumble-server --help``

### Mumble version

1.6.x

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

_No response_

### Relevant log output

```shell

```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Ibra2k**
Commit restores output from the `--help` and `-h` command when calling `mumble-server` by passing the help text from CLI11 to stdout.

Previously the `--help` was being swallowed by internal logger, since Mumble’s startup wraps CLI11 inside its own Murmur initializing logic that was detaching from the console.

So effectively the `--help` flag was being triggered and parsed but not displayed on user output terminal.

Closes #6934

### CODE REVIEW

File: src/murmur/main.cpp [hunk 1]
```diff
@@ -301,12 +302,22 @@ CLIOptions parseCLI(int argc, char **argv) {
...
-			qWarning("%s", error_stream.str().c_str());
-		} else {
-			qInfo("%s", info_stream.str().c_str());
+		if (e.get_exit_code() != static_cast<int>(CLI::ExitCodes::Success)) {
+			const std::string err = error_stream.str();
+			const std::string info = info_stream.str();
+
+			if (!err.empty()) std::cerr << err;
+			if (!info.empty()) std::cerr << info;
+			options.quit = true;
```
Comment (Krzmbrzl) [inline src/murmur/main.cpp]: why was this brought into the `if`? It seems that there is no functional change but code duplication by having the same statement unconditionally in the `if`. Instead, it seems like the `return` can also be factored out of the branched code 🤔

File: src/murmur/main.cpp [hunk 2]
```diff
@@ -368,7 +379,7 @@ int main(int argc, char **argv) {
 #endif
 		CLIOptions cli_options = parseCLI(argc, argv);
 		if (cli_options.quit)
-			return 0;
+			return cli_options.exitCode;
```
Comment (Krzmbrzl) [inline src/murmur/main.cpp:382]: Technically, this fixes a separate issue (exit code being swallowed) and ideally this should be in its own commit (can still be part of this PR though). However, this is minor enough for me to not really care…

**Comment by Ibra2k** [comment]
All checks have passed and the feedback from CodeRabbit has been address. 
The `--help` now prints to stdout and returns proper exit codes.

May someone please approve the workflow and review for merging.
Thank you!

File: src/murmur/main.cpp (hunk 1 above)
Comment (Ibra2k) [reply src/murmur/main.cpp]: I brought it to the `stdout` using `if` since the previous function was writing to the logging internally while `mumble-server` was detached. However for the return statements your completely right and i missed it, Ill fix it now

File: src/murmur/main.cpp (hunk 2 above)
Comment (Ibra2k) [reply src/murmur/main.cpp:382]: Yea that's my bad honestly, Completely slipped my mind, ill make sure to make a separate issue for it.

Comment (Hartmnt) [reply src/murmur/main.cpp:382]: If this really is a bug, the commit should fix it for the client, too. Because it will be most likely the same there.

**Comment by Hartmnt** [comment]
This fixes the problem. Out of curiosity, can you explain why this change was necessary in mumble-server, but not the mumble client?

File: src/murmur/main.cpp [hunk 3]
```diff
@@ -301,12 +302,19 @@ CLIOptions parseCLI(int argc, char **argv) {
...
 		app.exit(e, info_stream, error_stream);
 
-		if (e.get_exit_code() != static_cast< int >(CLI::ExitCodes::Success)) {
-			qWarning("%s", error_stream.str().c_str());
+		if (e.get_exit_code() != static_cast<int>(CLI::ExitCodes::Success)) {
+			const std::string err = error_stream.str();
+			const std::string info = info_stream.str();
+
+			if (!err.empty()) std::cerr << err;
+			if (!info.empty()) std::cerr << info;
```
Comment (Hartmnt) [inline src/murmur/main.cpp]:
```suggestion
			if (!err.empty()) {
				std::cerr << err;
			}
			if (!info.empty()) {
				std::cerr << info;
			}
```

File: src/murmur/main.cpp [hunk 4]
```diff
@@ -301,12 +302,19 @@ CLIOptions parseCLI(int argc, char **argv) {
...
 		} else {
-			qInfo("%s", info_stream.str().c_str());
+			std::cout << info_stream.str();
 		}
+
 		options.quit = true;
+		options.exitCode = e.get_exit_code();
+		return options;
```
Comment (Hartmnt) [inline src/murmur/main.cpp]: I don't think this return is necessary

**Comment by Ibra2k** [comment]
> This fixes the problem. Out of curiosity, can you explain why this change was necessary in mumble-server, but not the mumble client?

Well my thought process was that since the problem was occurring on the mumble-server i looked at the main.cpp file of it and since you guys mentioned it was working one person but not for another so I figured maybe there was a something/removed.

 And i noticed that since the addition to CLI11 we were having this problem so I figured that was it.
 
 I didn't think about the mumble-client since the problem was for the mumble-server command flag

File: src/murmur/main.cpp (hunk 4 above)
Comment (Ibra2k) [reply src/murmur/main.cpp]: I put the return in case parsing didn't go well due to an invalid flag or some other behavior. And it was a suggestion from code rabbit too since it was considered cleaner/safer.

File: src/murmur/main.cpp (hunk 2 above)
Comment (Ibra2k) [reply src/murmur/main.cpp:382]: This part wasn't part of the bug the main problem was the `qInfo` and `qWarning` functions that were not being displayed to screen. This was a suggestion from code rabbit when i was submitting my PR. But it mainly just acts as a code error catch when parse isn't successful.

Comment (Hartmnt) [reply src/murmur/main.cpp:382]: It makes absolutely no sense to fix this in the server but not the client. The code structure of server and client are almost identical in that regard.

Code Rabbit is only taking files into account that are being touched by a pull request and nothing more.

File: src/murmur/main.cpp (hunk 4 above)
Comment (Hartmnt) [reply src/murmur/main.cpp]: The next statement is literally the same return expression. I don't see why this return is "safer/cleaner", so please explain to me why this is needed from a code flow perspective. Maybe I am missing something, but maybe also consider that LLMs are not almighty.

**Comment by Hartmnt** [comment]
> > This fixes the problem. Out of curiosity, can you explain why this change was necessary in mumble-server, but not the mumble client?
> 
> Well my thought process was that since the problem was occurring on the mumble-server i looked at the main.cpp file of it and since you guys mentioned it was working one person but not for another so I figured maybe there was a something/removed.
> 
> And i noticed that since the addition to CLI11 we were having this problem so I figured that was it.
> 
> I didn't think about the mumble-client since the problem was for the mumble-server command flag

This entirely misses the point of my question. I know that there was a problem with mumble-server and not with mumble-client, since I was the one who reported the issue.

I want to know (without digging into it myself, because otherwise I could have done this entire MR myself), why the implementation before your PR was working for the client but not the server. If you look at both implementations you will find that they are almost identical (with regards to the CLI parsing). So why was this broken in the first place?

**Comment by Ibra2k** [comment]
> > > This fixes the problem. Out of curiosity, can you explain why this change was necessary in mumble-server, but not the mumble client?
> > 
> > 
> > Well my thought process was that since the problem was occurring on the mumble-server i looked at the main.cpp file of it and since you guys mentioned it was working one person but not for another so I figured maybe there was a something/removed.
> > And i noticed that since the addition to CLI11 we were having this problem so I figured that was it.
> > I didn't think about the mumble-client since the problem was for the mumble-server command flag
> 
> This entirely misses the point of my question. I know that there was a problem with mumble-server and not with mumble-client, since I was the one who reported the issue.
> 
> I want to know (without digging into it myself, because otherwise I could have done this entire MR myself), why the implementation before your PR was working for the client but not the server. If you look at both implementations you will find that they are almost identical (with regards to the CLI parsing). So why was this broken in the first place?

In the mumble client main.cpp there was no custom message handler (qInstallMessageHandler) and was using the default Qt message handler. Whereas in the mumble-server main.cpp that custom handler was called
before the cli parsing while detach was true so we had buffering.

File: src/murmur/main.cpp (hunk 4 above)
Comment (Ibra2k) [reply src/murmur/main.cpp]: > The next statement is literally the same return expression. I don't see why this return is "safer/cleaner", so please explain to me why this is needed from a code flow perspective. Maybe I am missing something, but maybe also consider that LLMs are not almighty.

yea your right i'll remove it

File: src/murmur/main.cpp (hunk 2 above)
Comment (Ibra2k) [reply src/murmur/main.cpp:382]: Yea i agree your right, should i make a commit to the client too? 

Because it completely went over me. I didn't I'd be allowed to make changes to the client also, since I was only tasked to fix the help flag.

But if you want me I can add it to the client main.cpp too.

Comment (Krzmbrzl) [reply src/murmur/main.cpp:382]: Yes, please also fix the issue in the client. In the end we'll want to have the return value fixes any the help message fix in two separate commits after all. That can be done during rebasing to adhere to our commit guidelines once you are done with everything else :)

**Comment by Hartmnt** [comment]
> In the mumble client main.cpp there was no custom message handler (qInstallMessageHandler) and was using the default Qt message handler. Whereas in the mumble-server main.cpp that custom handler was called before the cli parsing while detach was true so we had buffering.

Thanks for the explanation. I see it now:

We do ``qInstallMessageHandler`` for the server before parsing the CLI options. Our message handler logs to syslog and not to stdout/stderr.

While we do ``qInstallMessageHandler`` after the parsing of CLI options for the client when initializing the logger. And I think our client handler/logger logs to multiple places including stdout/stderr anyway.

**Comment by Hartmnt** [comment]
The only things missing for this PR are

* We want the exit code fix for the client, too. As stated above.
* The code formatting is not quite correct. Please check the PR-Check CI job log or use clang-format in version 10 to fix this.
* In the end we want 2 commits in this PR. One for the mumble-server cli output fix. And one for fixing the exit code in both server and client. Look up "git interactive rebase" to get an idea on how it is done.

If you have any further questions, feel free to ask

**Comment by Ibra2k** [comment]
> The only things missing for this PR are
> 
>     * We want the exit code fix for the client, too. As stated above.
> 
>     * The code formatting is not quite correct. Please check the PR-Check CI job log or use clang-format in version 10 to fix this.
> 
>     * In the end we want 2 commits in this PR. One for the mumble-server cli output fix. And one for fixing the exit code in both server and client. Look up "git interactive rebase" to get an idea on how it is done.
> 
> 
> If you have any further questions, feel free to ask

I used clang-format version 18 since i couldn't get the older version. I hope it still has the proper formatting, if not please notify and ill change it manually right away.

**Comment by Hartmnt** [comment]
> I used clang-format version 18 since i couldn't get the older version. I hope it still has the proper formatting, if not please notify and ill change it manually right away.

We are happy, if the CI is happy. For now please include the formatting fix in your existing 2 commits.

**Comment by Ibra2k** [comment]
> > I used clang-format version 18 since i couldn't get the older version. I hope it still has the proper formatting, if not please notify and ill change it manually right away.
> 
> We are happy, if the CI is happy. For now please include the formatting fix in your existing 2 commits.

Can you explain what you meant by CI? I didn't get it.
And just to be sure I need to combine the 2 commits into 1 like squash them?

**Comment by Krzmbrzl** [comment]
> Can you explain what you meant by CI? I didn't get it.

CI is short for "continuous integration". These are the builds and checks that are run for every commit (on GitHub they are listed here under "checks". In order for your PR to be accepted all CI runs (checks) need to pass.

>  And just to be sure I need to combine the 2 commits into 1 like squash them?

You'll have to disentangle your changes first. To do that, squash all three of your commits and then do a `git reset HEAD ~1` to "uncommit" the combined commit (the result of the squash). Now `git status` will show you the changed files. All those files need to be formatted via clang-format. Now, use `git add -p` to add only those changes related to the fix of the CLI output and commit them. Then add the remaining changes (related to the exit code fix) and commit those (note that this commit should have TYPE `FIX(client, server)` as both components are affected by this).

**Review by Hartmnt — APPROVED** [review]
Tested, works as advertised

**Comment by Hartmnt** [comment]
Thank you very much for fixing this :tada:

**Comment by Ibra2k** [comment]
> Thank you very much for fixing this 🎉

Thank you for allowing to work on it and guiding me through the process!!
